### ISSUE TITLE
Thumbnail Generation

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#1]
Because the frontpage is way too heavy as it is, and the easiest way is to generate thumbnails for display, either when an image is uploaded, or when it is first accessed.

For a CDN, though, generating the thumb when uploaded would be best.

**Comment by ThomasKerman** [comment]
Closing this as the thumbnails are not generated, but the headers get placed with CSS

**Comment by phmayo** [comment]
Well, then we need thumbnail generation, instead of using ginormous images on the frontpage.

Placing this on Roadmap, though, instead of for a SpaceDock release.

**Comment by sharksharkco** [comment]
This may be related, https://github.com/KSP-SpaceDock/SpaceDock/issues/57#issuecomment-185403879

**Comment by ThomasKerman** [comment]
I was already thinking about implementing a crop window for the thumbnails

**Comment by sharksharkco** [comment]
I gotta say I think eliminating the banner has more pros than the one con of no banner.
- no need to add additional functionality
- set size restrictions/resize thumbnails on upload
- no stretching/cropping on different screen sizes
- opens up the description as an open canvas, those that use banners can still use this area to display a full width banner that won't be skewed/cropped by the fixed height of the banner

**Comment by godarklight** [comment]
This is probably where most of our traffic is going, the main page images are probably bigger than most mods.

@sharksharkco Upload size restrictions are *lame*, let's go with libgd or whatever and just resize them a bit smaller.

I'd keep mod banners, they serve as the thumbnail image too. If anything maybe we can resize them down if they are overly big, but don't go too terrible on the quality - they are banners after all.

**Comment by godarklight** [comment]
I'm taking this one, I'll get it out of the way tomorrow.

**Comment by GenPage** [comment]
@godarklight :+1: on upload size restrictions being lame and going with a lib to resize.

I vote to keep the banners as well, but only display on mod view page.

**Comment by godarklight** [comment]
I did a thing!

Implemented via 8f7fa597c1247945a27664645fd76f3423222548 and fe64501900d6811b4ec346fcece59bee7a85ee7e.
