### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by EIREXE** [KSP-SpaceDock/SpaceDock#10]
Add categories from ModulousSmash/Modulous

You guys can suggest some

**Comment by phmayo** [comment]
Instead of categories: Tags? Same difference, but you can have a mod in Science *and* Parts that way.

Dmagic's Orbital Science and Crowd Sourced Science come to mind: Both are science mods, but one has parts, the other adds more flavor to the game.

**Comment by EIREXE** [comment]
I used tags in modulous back in the day, people hated them, they worked like booru tags.

**Comment by ThomasKerman** [comment]
I support Tags too, because there's such a variety of Mods that we can't put them into 10 or 20 categorys - every mod does something different. But if you guys work out a proper categories system, I'd be happy to implement it.

**Comment by EIREXE** [comment]
@ThomasKerman I already have an implementation done from my own site (modulous.net).

**Comment by V1TA5** [comment]
tags are a better idea
