### ISSUE TITLE
Hover over thumbnail for Follow/Download from browse

### ISSUE THREAD

**Issue by sharksharkco** [KSP-SpaceDock/SpaceDock#103]
Mousing over an item in browse/search would display the Follow/Download button over the thumbnail.
Make title, excerpt, and area around Follow/Download buttons click through to mod page.

**Comment by godarklight** [comment]
This sounds like a nice usability feature, I'm unaware of how hard it would be to implement though - I've not poked into our framework :)

**Comment by V1TA5** [comment]
could be added but the space is now occupied by the description.
