### ISSUE TITLE
Featured Mods - Selection and Rotation

### ISSUE THREAD

**Issue by inigmatus** [KSP-SpaceDock/SpaceDock#107]
I just wanted to put it out there that on Mondays, we should wipe the feature mod slate clean, and that I think all admins of the site should pick a new featured mod, one per admin, that will be featured until the next Modding Monday. We could start this next Monday, Feb 29, 2016, if there is consensus on this.

**Comment by inigmatus** [comment]
I also posit that there should be no limits to how many times a mod be picked by an admin to be featured, but only one per admin permitted (to keep the list down).

**Comment by NecroBones** [comment]
I'd be good with that. Otherwise it ends up being an arbitrary list, with some mods featured forever. On KerbalStuff, one of mine got featured, none of the others, and of course even that one got pushed down the list over time. Having some sort of rotation or replacement of the list allows for more mod exposure over time.

**Comment by inigmatus** [comment]
Anyone object to a weekly rotation starting this Monday?

**Comment by godarklight** [comment]
This isn't a bad idea, although I probably won't be picking myself as I don't use a lot of mods :)

**Comment by V1TA5** [comment]
darklight you never pick yourself that makes you such a sympathic person :)

i suggest the following:
replace the featured mods with top rated, newcomers and top picks.

top rated would be determined by user ratings (and they would also be able to write reviews)

up and coming would be determined by amount of stars in agiven time

top picks would be determined by the amount of modpacks including the mod

this would give user accounts more use and some say in whats shown

we can also add most viewed to the mix if we want to.

all those mods would show in a slidshow (wither as stack or as filmstrip horizontaly scrolling) in random order
in addition we can have pages for each type like the featured has now.

im also all for the ability to embed video reviews

voting:
users can vote in several categorys like update frequency, responstime on new ksp versions,
the usual like concept, integration into the game, art (if any), sound (if any), stability, play value and so on.

if we do that every mod has the chance to get promoted and i hope no one wil complean that we pick the wrong ones in their opinion.

**Comment by inigmatus** [comment]
for now i recommend a weekly wipe of featured mods, and all admins can pick one (and only one) mod to feature. poor sport to pick oneself, but admins should be free to pick any mod, even the same mod week over week.

**Comment by DMagic1** [comment]
I would recommend staying away from any type of user feedback on the site. 

Any kind of text review just provides another space for people to post issues; Curse does this (with different reviews for Curse and CurseForge...) and they seem to be completely ignored for the most part. Feedback should be provided on the forum and/or GitHub repo if applicable.

I suppose star-type ratings would be fine, but probably wouldn't be too valuable. I suspect they would end up like the forum thread ratings; if someone likes something they will give it five stars and will otherwise be indifferent.

**Comment by inigmatus** [comment]
I think we're going with a regular Modding Monday schedule of wiping all featured mods, and each admin then picking their personal favorite until the next Modding Monday. Indifferent admins can solicit the community for ideas or just pick a random one. The idea being that the reward of working as an admin is to have the right to pick one featured mod for the week.

I also concur that to keep things simple that we consider holding off on a community rating system for now.  The fact that downloads and followers and forum links are posted should be enough to convince a shopper about its quality. just my 2 cents.

**Comment by Unknown601** [comment]
@inigmatus :-/ not a bad idea but we (i don't know about the rest of you) work as admins because we want to make SPACEDOCK flourish, not to pick a featured mod every week, to me that's just something that is done to keep the home page fresh.

**Comment by inigmatus** [comment]
@Unknown601 one man's work is another man's reward. :P  Granted, if we wanted to offer mod picking responsibilities to selected individuals, I'm sure we'd have a queue of applicants extending beyond espernet.  For the record, I don't think anyone joined SpaceDock to pick mods. I think we all joined it to give the community back a service that was unceremoniously abandoned (pls no discussion on that here though, heh).

**Comment by Unknown601** [comment]
@inigmatus ok :) :P Well i'm in on selecting a featured mod every week

**Comment by V1TA5** [comment]
if we have the time at some point we can do personal featured mods per visitor based on web statistics from piwik. it comes with an api we can use.

**Comment by godarklight** [comment]
We... we should change our features sooner or later :P

**Comment by inigmatus** [comment]
Its Modding Monday! I've wiped the previously featured mods. Go out and pick a new one! One per admin.

**Comment by inigmatus** [comment]
Its Modding Monday! I've wiped the previously featured mods. Go out and pick a new one! One per admin.

**Comment by inigmatus** [comment]
closing issue as we have a fairly descent system of notifying the team in IRC - and I uh.. have no problem appointing mods for empty slots. heh. :)
