### ISSUE TITLE
Mod title element should have a smaller font if title is too big

### ISSUE THREAD

**Issue by RockyTV** [KSP-SpaceDock/SpaceDock#120]
Right now, the mod title element messes up the mod div, eventually messing up the entire layout of the page because of a big title. Here's how it looks like:
![](http://i.imgur.com/xLgMNHq.png)

![](http://i.imgur.com/Zjl63J7.png)

Suggestions:
- Reduce font size according to title length
- Specify a max length for mod names

**Comment by FrikFry** [comment]
I fixed this in #116. Someone needs to push dev into master and update spacedock.info.
