### ISSUE TITLE
[ops] Please enable Login with Github/Google

### ISSUE THREAD

**Issue by avivey** [KSP-SpaceDock/SpaceDock#121]
To allow register/login without requiring password.

The code is already there (Or was, a couple of weeks ago), [oauth.md](https://github.com/KSP-SpaceDock/SpaceDock/blob/dev/oauth.md) has the configuration instructions.

**Comment by V1TA5** [comment]
wont happen. 
i misstrust large companies like google because they earn money by selling userdata. 
My goal ist to keep as much inhouse as i can, because i feel responsible for the data given to me.
(as soon as i get arround doing it i will host all external js and fonts on spacedock too)

**Comment by avivey** [comment]
ack.
