### ISSUE TITLE
[Enhancement]Add A tagging System!

### ISSUE THREAD

**Issue by ThaZeus** [KSP-SpaceDock/SpaceDock#124]
One thing that kerbal stuff lacked was a tagging system so for example authors of mod expansions(like the MANY BD armory expansions.) Could tag their work "expansion for ________" or simply the mod the expansion is for. I thought this because i thought how nice it would be to see only expansions to BD armory (like NKD)

**Comment by TN-1** [comment]
Something similiar to this was proposed in #101
