### ISSUE TITLE
Switch all web traffic over to HTTPS rather than HTTP

### ISSUE THREAD

**Issue by politas** [KSP-SpaceDock/SpaceDock#125]
The World Wide Web is transitioning to [security by default](https://en.wikipedia.org/wiki/Secure_by_default). Some web browsers are already flagging all http: URLs as a security issue for users. It would be much better to transition to secure traffic and implement an automated certificate renewal system (if this has not already been implemented) before users start being concerned about man in the middle attacks.

**Comment by V1TA5** [comment]
SpaceDock supports https allready. i cant force it because of other websites on the host that have problems with it. but most browsers do https first anyway.

**Comment by Orkeren** [comment]
@V1TA5 whether you use nginx, apache or IIS (shudders), you can force HTTPS on a domain basis. So this really shouldn't be an issue.
