### ISSUE TITLE
Remarkably poor download speeds

### ISSUE THREAD

**Issue by DuoDex** [KSP-SpaceDock/SpaceDock#126]
Download speeds appear to be tanking across the globe, I spoke to some folks in the IRC who said they noticed it too, so it's not just a local issue. Actual speeds hover from 200 kb/s to 100.

**Comment by ThomasKerman** [comment]
This sounds like a local issue for me (maybe sth. with your connection). The site is much faster for me than KerbalStuff

**Comment by DuoDex** [comment]
Might have been a local thing, speeds seem to be back up to normal.
