### ISSUE TITLE
Document the spacedock API

### ISSUE THREAD

**Issue by godarklight** [KSP-SpaceDock/SpaceDock#129]
I'll tackle this one - currently the API has no documentation, and it would be kind of nice for people interested in interfacing with SpaceDock.

**Comment by FrikFry** [comment]
Just as a note, its not quite *completely* undocumented. We do have https://github.com/KSP-SpaceDock/SpaceDock/blob/dev/api.md

That being said, that document could certainly be expanded significantly.

**Comment by godarklight** [comment]
Err, apparently I'm blind - I'll close this for now, sorry about that :P
