### ISSUE TITLE
Navbar menu search at mobile size

### ISSUE THREAD

**Issue by sporeventexplosion** [KSP-SpaceDock/SpaceDock#130]
**Description (What went wrong?):**
The current Bootstrap CSS for the navbar search seems broken when at mobile resolution (i.e. the resolution which makes the hamburger menu show). The search bar becomes very narrow, pulled to the right, and shows white bars above and below (may be because of a "hack" used to display the search bar).

**Reproduction Steps (What did you do?):**
Resize the window width until the navbar menu changes to a hamburger menu button, open the menu, and the broken search bar can be seen.

**Expected Behavior (What do you think should have happened instead?):**
First, the white lines possibly should not be present, and it may be better if the search bar filled the whole width of the menu instead.

Also, the issue doesn't seem to exist when using the example navbar from Bootstrap, so this is likely because of custom styling.

**Environment (OS/Browser/Plugins/etc):**
Should be a browser-independent CSS problem. Reproduced in either Firefox or Chrome

**Comment by sporeventexplosion** [comment]
![image](https://cloud.githubusercontent.com/assets/8079858/13544849/ef3ec220-e2b6-11e5-8a72-794263b1d96f.png)
Seems to have something to do with `float: right` that applied regardless of media query. The search box was fine when I disabled the property (see image);

**Comment by HebaruSan** [comment]
The original description sounds familiar for anonymous users:

![image](https://user-images.githubusercontent.com/1559108/140977990-48ce4546-061a-46df-b780-fa5312028138.png)

But for logged in users, the search bar disappears completely in mobile:

![image](https://user-images.githubusercontent.com/1559108/140977629-a0ca6c36-5b09-466e-9d92-81ec2faa04e1.png)

Also the Log Out option is gone, bizarrely.

**Comment by HebaruSan** [comment]
> Also the Log Out option is gone, bizarrely.

Aha! The menu _scrolls vertically_! And that's also where the search box was:

![image](https://user-images.githubusercontent.com/1559108/141010899-b8774728-1de1-4399-ba71-fb5dc3739a59.png)
