### ISSUE TITLE
File Size Display

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#131]
This is more of a feature request.  Nothing is wrong.

I would like to see a file size field for those on limited bandwidth connections. 

It would help with people on Satellite and cellphone (and other metered) data connections.  They could choose which files to get and when instead of guessing when it would be safe to download the large ones.

Az

**Comment by TN-1** [comment]
I personally think that is a good idea, Of course it would all depend on how difficult it would be to implement it.

**Comment by inigmatus** [comment]
I like it.

**Comment by ILM126** [comment]
There should also be a setting where the user can set the max for file downloads, and will warn the user if the file is getting close to that per mod limit.

**Comment by godarklight** [comment]
Putting the size on the download button isn't a bad idea actually. But hell no to max download limit.

**Comment by GenPage** [comment]
Agreed, a file size can be reported to allow users/interfaces to report download progress but setting a max download limit is something that should be implemented on a client interface not on SpaceDock.

**Comment by DasSkelett** [comment]
We have the zip sizes displayed in the download buttons since #206 now.
I don't fully understand the limit request, but if users only want to download a certain amount per day, they should be able to pull up a calculator.
