### ISSUE TITLE
kOS scripts section/subsite

### ISSUE THREAD

**Issue by hashashin** [KSP-SpaceDock/SpaceDock#132]
As there's nothing besides ksp forum or github to find them, it would be great if Spacedock also can host scripts for KOS, perhaps in a section or in a subsite. 

Thanks.

**Comment by TN-1** [comment]
If you are a reddit user, have a look at /r/kos. It's a fairly active community and all the developers are active there. There's a lot of script sharing and there are links all over the place to git repos.  
Something centralised would be nice though.

**Comment by HebaruSan** [comment]
This is a duplicate of #101 (asking for an "add-ons to add-ons" feature in general rather than just for kOS).
