### ISSUE TITLE
Dark theme highlight color

### ISSUE THREAD

**Issue by IceSentry** [KSP-SpaceDock/SpaceDock#134]
I really like the fact that you added the option for a dark theme, but you change the nice blue color to some kind of purple. What I would suggest is to not change the colors of the buttons/navbar. The original blue is a nice color that could go well with a dark theme the fact that it changes color right now is a bit weird. Having the same color in both themes would make for a more consistent experience.

**Comment by V1TA5** [comment]
darktheme was removed but maybe custom colors will be added.
