### ISSUE TITLE
KSP version selector

### ISSUE THREAD

**Issue by IceSentry** [KSP-SpaceDock/SpaceDock#136]
After the current pre-release of 1.1 it would be really nice to have a feature to sort mods based on supported version. For example having a dropdown menu at the top of the site that let's you select what version of KSP you want to use. This way if I want mods that work for 1.1 I don't have to look through a bunch 1.0.5 mods.

**Comment by godarklight** [comment]
Although this isn't perfect, you can type in the search bar ksp:1.0.5

**Comment by IceSentry** [comment]
This is indeed better than nothing, but this could also be implemented as a feature in the future.

**Comment by HebaruSan** [comment]
Duplicate of #174
