### ISSUE TITLE
Deleting a version does not clear the tag/delete the files

### ISSUE THREAD

**Issue by StupidChris** [KSP-SpaceDock/SpaceDock#137]
Relevant conversation to this issue [here](http://pastebin.com/1CCnntVU).

Basically: deleting a version tag from the available downloads does not clear the associated tag or delete the binaries. Creating a new upload with the same tag then fails because the tag still exists and files cannot be overwritten.

Apparently an easy fix :p

**Comment by godarklight** [comment]
We could either delete the mod here: https://github.com/KSP-SpaceDock/SpaceDock/blob/dev/KerbalStuff/blueprints/mods.py#L475

Or just allow an overwrite:
https://github.com/KSP-SpaceDock/SpaceDock/blob/dev/KerbalStuff/blueprints/api.py#L678-L679

**Comment by godarklight** [comment]
Fixed via c24df4e2a00a423825bf93c689ba4e70f3c10d54
