### ISSUE TITLE
Changelog editing text white on white when uploading new version on dark theme

### ISSUE THREAD

**Issue by StupidChris** [KSP-SpaceDock/SpaceDock#138]
Description (What went wrong?):

When creating a new version with the dark theme on, the changelog text editing box has white text on a white background, rendering it invisible.

Reproduction Steps (What did you do?):

1) Switch on dark theme
2) Update an existing mod
3) Try to type into the changelog box

Expected Behavior (What do you think should have happened instead?):

Text should be black so we can you know... read it :p

Environment (OS/Browser/Plugins/etc):

Windows 10 x64, Chrome

Extra Information (Screenshots/Error Messages/Javascript Console Output):

![](http://i.imgur.com/ZBdFaKR.png)

![](http://i.imgur.com/U10zk1A.png)

**Comment by godarklight** [comment]
I fixed a thing!
