### ISSUE TITLE
Kerbal Space Program link disappears when viewing the Recently Updated or Popular Mods page

### ISSUE THREAD

**Issue by DMagic1** [KSP-SpaceDock/SpaceDock#139]
Description (What went wrong?):
The KSP link in the title bar isn't always present.

Reproduction Steps (What did you do?):
Click on either the Recently Updated or Popular Mods links at the KSP home page.
Edit: Actually it seems to be lost when clicking on any of the Browse... links.

Expected Behavior (What do you think should have happened instead?):
The Kerbal Space Program link should always be visible while in a KSP-related page.

Environment (OS/Browser/Plugins/etc):
Windows 10, Chrome

**Comment by godarklight** [comment]
This may have been caused when beta accidentally took over production for a bit :P

**Comment by V1TA5** [comment]
hopefully fixed in code ....if not reopen
