### ISSUE TITLE
Some white space or borders for the description text

### ISSUE THREAD

**Issue by DMagic1** [KSP-SpaceDock/SpaceDock#140]
The mod description text (the same applies to the stats page) runs right up to the border of the browser. This can look a little odd and make reading more difficult than it should be. A little bit of white space around the edges would help.

Environment (OS/Browser/Plugins/etc):
Windows 10, Chrome

**Comment by StoneBlue** [comment]
I agree.... I think an actual color would help break up all the white-space... Especially for people who's eyes are sensitive to light, and/or who spend lots of time in front of a computer

**Comment by HebaruSan** [comment]
I think this got fixed in a5a2f79b118e67871319cee0403ce761e2d97603, which created a `space-left-right` CSS class with left and right margins of 2.5mm. The descriptions look OK to me now.
