### ISSUE TITLE
[Feature] Sort mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-SpaceDock/SpaceDock#141]
The mods should be sorted when displayed, the sort should be in an understandable order.  Right now they are just a jumble

**Comment by godarklight** [comment]
I believe they are sorted by popularity, but yeah it is a bit of a mess.

**Comment by linuxgurugamer** [comment]
That's, ummmm, not smart (trying to be polite here :-)   )

At least put in an alphabetical sort.  Since there is a sort going on, it should be easy enough to change what's being sorted on.

**Comment by linuxgurugamer** [comment]
Was this done, I don't see any way to specify a sort

**Comment by WuphonsReach** [comment]
This would be important on the profile page where I can see all the mods that I'm following.  Being able to sort by name / author / last update / latest supported version, would make that page much more useful.

**Comment by HebaruSan** [comment]
There is some sorting, based on which URL you click:

- https://spacedock.info/kerbal-space-program/browse/updated
- https://spacedock.info/kerbal-space-program/browse/new
- https://spacedock.info/kerbal-space-program/browse/top
- https://spacedock.info/kerbal-space-program/browse/all (same as 'top')

But it should be clearer and easier to switch between lists, as well as see which options are available.

**Comment by HebaruSan** [comment]
Did this in #481.

![image](https://user-images.githubusercontent.com/1559108/226648814-d8002c8a-4810-4049-acfe-11788478f88e.png)
