### ISSUE TITLE
[Feature] Improve search/filter capabilities

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-SpaceDock/SpaceDock#142]
The search is somewhat simple right now.  it would be nice to have more features, or at least some additional filters such as:
KSP version
updated within
Author
etc

**Comment by linuxgurugamer** [comment]
I understand there is an advanced search, but there is no indication of that on the spacedock page

**Comment by linuxgurugamer** [comment]
I see the "advanced search" button, so at least there is something.
But ( and I know the work involved and appreciate the work you do), could you create a search page to make it easier for people?  The way it is is kind of geeky, and the average person won't understand it.

**Comment by linuxgurugamer** [comment]
Search is still a little obtuse

**Comment by HebaruSan** [comment]
The current advanced options are a bit dubious:

![image](https://user-images.githubusercontent.com/1559108/83318037-da9d7380-a1f6-11ea-8718-0901f4489c5d.png)

- You can see an author's mods on their profile
- There's only one `game` now anyway
- Who cares how many downloads or followers it has?

Searching by version is the only one that seems solidly useful. Providing easier access to a bunch of (nearly) useless should probably wait until after more useful ones are added.

**Comment by HebaruSan** [comment]
`ver` should optionally support `<` and `>`, so you can limit the search to everything from KSP 1.10 and later, for example.

And probably also partial version matching, so `ver:1.12` would match 1.12.0–1.12.2.
