### ISSUE TITLE
(Feature) add icons to the various games

### ISSUE THREAD

**Issue by Joshwoo69** [KSP-SpaceDock/SpaceDock#143]
Description:
says what is on the tin.. there are some links for the variosu games:
Factorio : https://eu6.factorio.com/assets/img/factorio-logo-pack.zip (presskit)
Stardew valley: http://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg?t=1458942334 (steam)
Starbound: http://staging.playstarbound.com/wp-content/uploads/2016/02/starboundlogo.png (logo from main site)

**Comment by TN-1** [comment]
Not too sure what you want, SpaceDock is only for Kerbal Space Program mods

**Comment by Joshwoo69** [comment]
VITAS probably want to expand into other games... :AFAIK from irc.

**Comment by V1TA5** [comment]
Covers for games will be added soonish.
