### ISSUE TITLE
Factorio version list

### ISSUE THREAD

**Issue by MrDrummer** [KSP-SpaceDock/SpaceDock#144]
Description (What went wrong?):
The list only goes from 0.1.0 up to 0.11.1 - factorio is now on 0.12.30, 50 versions on. When I enter a custom version into the box to the left of the dropdown menu (0.12.30), it gives a basic "Internal Server Error" page,

Reproduction Steps (What did you do?):
Create a mod for Factorio, and click the dropdown menu for the version.

Expected Behavior (What do you think should have happened instead?):
Either allow custom versions to be entered, or keep updating the mod versions list, either automatically or manually.

**Comment by godarklight** [comment]
We'll have to update the list.

**Comment by V1TA5** [comment]
added 0.12.30 updating version numbers is a manaual process (cant find a source for game versions on the net)

**Comment by MrDrummer** [comment]
I get an error at the bottom of the mod creation page that says "Game version does not exist". (0.12.30 is selected - same thing happens for 0.12.0)

**Comment by Joshwoo69** [comment]
https://forums.factorio.com/viewforum.php?f=3&sid=404d12bddfa2f410d67298e4595f1de8
(all the version lists)
