### ISSUE TITLE
Some visual bugs

### ISSUE THREAD

**Issue by jenyaza01** [KSP-SpaceDock/SpaceDock#145]
Just load any page except main (I load http://spacedock.info/kerbal-space-program)

Something wrond with words "Kerbal Space Program" on this screen. (mark red)
![spacedock](https://cloud.githubusercontent.com/assets/13692655/14411071/cf647eca-ff46-11e5-8036-b08dd29ee7a2.png)

Has Windows 7, 1366x768, Google Chrome, 100% site scale.

And one improvement idea: place description text not from top of the mod tile, but center it (mark green)
Thanks.

P. S. maybe, i look on site under design testing... it really looks cool now.

**Comment by jenyaza01** [comment]
Used chrome`s page source code editor (f12)
Moved "a class="gamename" into the "span class="darker"

Get 
![image](https://cloud.githubusercontent.com/assets/13692655/14411282/8da004d6-ff4c-11e5-82c8-c81eeaa2f74d.png)

![image](https://cloud.githubusercontent.com/assets/13692655/14411266/fe84e744-ff4b-11e5-8fac-9d03ddc64874.png)

**Comment by Joshwoo69** [comment]
![screenshot_2016-04-11-10-15-14](https://cloud.githubusercontent.com/assets/7894419/14415151/740e3452-ffce-11e5-9488-95608bcce640.png)
![screenshot_2016-04-11-10-15-01](https://cloud.githubusercontent.com/assets/7894419/14415153/84535b62-ffce-11e5-8e0a-0ba47c2eef7d.png)

same for android users

**Comment by jenyaza01** [comment]
Reopened SpaceDock... and it looks like intended.
Both title
![1](https://cloud.githubusercontent.com/assets/13692655/16678382/446c65a8-44e7-11e6-8c82-8efd0a836a23.PNG)
and dropdown menu 
![2](https://cloud.githubusercontent.com/assets/13692655/16678475/105bb556-44e8-11e6-97c1-e47350ad64cb.PNG)
are fixed now. If so, I can close issue as a solved.
(if you need, you can reopen it)
