### ISSUE TITLE
Development Versions

### ISSUE THREAD

**Issue by HeroOfFire45** [KSP-SpaceDock/SpaceDock#146]
I'm not a proper contribrutor yet, but I wanted to bring up the fact that the development version of KSP 1.1 is availible to the general public now. Should we add warnings or something to tell people the mod is for a in-development version? (At least label all mods for Prerelease 1.1 "1.1-pre" or something.)

**Comment by HebaruSan** [comment]
SQUAD stopped doing public pre-releases.
