### ISSUE TITLE
Unable to Connect - 

### ISSUE THREAD

**Issue by Xandercage22** [KSP-SpaceDock/SpaceDock#150]
Description (What went wrong?):
I have tried and failed multiple times on multiple platforms to access spacedock.info. The only successful attempt was on my phone using 4G. It fails while connected to wifi, leading me to believe the problem is somehow with my network, but I have no idea what it could be. I don't have any firewalls or security software running at any point between my browser and ISP, and haven't found any settings that would effect a website loading.

Reproduction Steps (What did you do?):
Open a tab, type "spacedock.info" in the navigation bar and press enter, or click a link

Expected Behavior (What do you think should have happened instead?):
I kind of feel like the website should have loaded. But it didn't. Now I'm very confused.

Environment (OS/Browser/Plugins/etc):
OS X 10.11.4 (13 Inch Late 2013 rMBP)
- Firefox 45.0.2
  - uBlock 0.9.5.0.1 (Disabled for test)
  - NoScript! 2.9.0.11 (Disabled for test)
- Safari 9.1
  - AdBlock 2.40.1 (Disabled for test)

iOS 9.3.1 (iPhone 6S)
- Safari
  - Purify 1.2.2

Netgear WNDR4300
- Firmware Version V1.0.2.80

Extra Information (Screenshots/Error Messages/Javascript Console Output):

<img width="1280" alt="screen shot 2016-04-20 at 1 04 21 am" src="https://cloud.githubusercontent.com/assets/18567626/14665166/7cce1b6a-0696-11e6-9e68-78e8d182e8db.png">
<img width="1280" alt="screen shot 2016-04-20 at 1 04 44 am" src="https://cloud.githubusercontent.com/assets/18567626/14665167/7cce380c-0696-11e6-9bd8-bb642739eaeb.png">
<img width="1280" alt="screen shot 2016-04-20 at 1 05 12 am" src="https://cloud.githubusercontent.com/assets/18567626/14665169/844f6970-0696-11e6-9dda-9857b665b412.png">

![img_1688](https://cloud.githubusercontent.com/assets/18567626/14665352/1f88e6a4-0698-11e6-8a42-3fc0f2af8232.PNG)
![img_1690](https://cloud.githubusercontent.com/assets/18567626/14665351/1f8518da-0698-11e6-96b8-0401a67ebda4.PNG)

**Comment by V1TA5** [comment]
have you checked if a) you can connect to other sites b) nslookup spacedock.info returns some ip (and please write that ip here) c) ping 5.9.16.54 gets the host
for me it sounds like a problem on your end or with the dns

**Comment by Xandercage22** [comment]
A) Yes, this is the only site I've ever had an issue with. 
B) Server:  192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	spacedock.info
Address: 5.9.16.54
C)92 bytes from 192.168.1.1: Destination Host Unreachable
Vr  HL  TOS   Len      ID    Flg   off   TTL  Pro   cks           Src             Dst
 4   5     00    5400   0718   0   0000  3f     01   9da5  192.168.1.5   5.9.16.54 

It could very well be a problem on my end, my knowledge of networking is extremely basic (feel free to read as non-existent. Seriously, I had to Google nslookup because I'd never heard of it before.) so I'm at a complete loss.

**Comment by V1TA5** [comment]
seems to be a routing problem. we arent your net technician but i can give you a few tips:
if youre on windows try "route print" and see if 0.0.0.0 is connected to 192.168.1.1 


check if there are some entries starting with 5.x.x.x if so you have to remove them
(maybe hamachi they used to simply use ip ranges that they had no right to use)

on windows go into network settings->adapters hold alt so the menu bar appears and select something like extended or advanced 
youll get a list with your adapters and arrows where you can reorder them
make sure your lan adapter is the first one in the list

also on windows you can use "tracert 5.9.16.54" to check on wich node between your computer and the server the connection is broken

i hope that helps
if so: theres a donation button on spacedock :D

**Comment by Xandercage22** [comment]
I appreciate the tips, but I'm on a Mac so I'm not sure how useful they'll be. I also really appreciate the swift responses. If I ever make it to spacedock, I'll be sure to donate :)

**Comment by godarklight** [comment]
Umm, doing things over git issues here might be a bit slow. Can you jump on our IRC so we can talk real time?

There's a chat button on the spacedock menu (or #spacedock on esper if you have an IRC client)

**Comment by Xandercage22** [comment]
Just saw this, logging on now.

**Comment by Xandercage22** [comment]
Are all the files on spacedock compressed? If so, I'll just use my phone's hotspot to access the site instead of my home network since that's where the problem seems to be and I don't know how to fix it.

**Comment by godarklight** [comment]
The mod downloads are zips so yes, but it's probably a firewall problem. Virus scanners also like to pretend they are firewalls too, and then there's morally questionable programs like peerguardian :P

**Comment by Xandercage22** [comment]
I just tried on my laptop using my phone's hotspot and it connected right away, so it's gotta be something with the router, modem, or my ISP. Like I said, I didn't have anything like that running while I was testing this out, and as far as I know the router doesn't even have a firewall available.

**Comment by HebaruSan** [comment]
Closing stale support ticket.
