### ISSUE TITLE
Blue Hawk Industries - download links are dead

### ISSUE THREAD

**Issue by plague006** [KSP-SpaceDock/SpaceDock#153]
This mod: https://spacedock.info/mod/519/Blue%20Hawk%20Industries has 2 versions in the changelog and both of the downloads are 404. I'm not sure if they're author-removed or if it's an error on spacedock's end.

My inclination is that it's not author-initiated due to the author's posts in the ksp forum thread.

> User: Is there a different link available? SpaceDock keeps giving me a 404. 
> Author: There is not no. The link is working fine on mine end so Im not sure what to tell you sorry 

Relevant thread: http://forum.kerbalspaceprogram.com/index.php?/topic/136721-blue-hawk-industries/

**Comment by DasSkelett** [comment]
The entire mod is now a 404, I guess it's gone.
