### ISSUE TITLE
Thumbnail Quality Very Low

### ISSUE THREAD

**Issue by toadicus** [KSP-SpaceDock/SpaceDock#156]
Description (What went wrong?):
SpaceDock generated some very low-quality jpg thumbnails, which look really bad when text is present.

Reproduction Steps (What did you do?):
I just sat here and watched.

Expected Behavior (What do you think should have happened instead?):
Thumbnail quality should be high enough that text doesn't render them completely hideous.

Environment (OS/Browser/Plugins/etc):
All the browsers.

Extra Information (Screenshots/Error Messages/Javascript Console Output):
Screenshot of three of my mods with heinous-looking compression around the text making them look bad:
![image](http://media.home.hawkbats.com/10uwnL472Z62.png)

thumbnail.create specifies a jpeg quality of 50.  That seems really low when coupled with 320px low-rez images.  Perhaps there is another value between 50 and 100 that would result in better text appearance?

**Comment by godarklight** [comment]
Initially I picked 320px in the old design when they were actually thumbnails, but the redesign has made this worse as they are much bigger now.

I believe @V1TA5 intends to either to multiple levels or up the resolution a fair bit in the redesign.

**Comment by HebaruSan** [comment]
Default quality was bumped to 80% in #311 along with other improvements.
