### ISSUE TITLE
Mod not being added to modpack

### ISSUE THREAD

**Issue by Cy4nX** [KSP-SpaceDock/SpaceDock#158]
Description:

When I tried to put a mod into my modpack, nothing happened. Is this a bug or am I just doing it wrong?

Reproduction Steps:
1. I copied the name of the mod word for word (Astroniki Sunflare for Scatterer)
2. I pasted it in the 'Mod Name...' box on the 'Edit Pack' page
3. I clicked the 'Add Mod' button
4. It sent me to the page for the modpack... WITH NO MOD!

Expectations:

The mod would be added to the modpack

Environment:

Google Chrome v50.0.2661.102 (64-bit)
Mac OS X v10.10.5

Screenshots:

<img width="1269" alt="screen shot 2016-06-08 at 15 41 05" src="https://cloud.githubusercontent.com/assets/18290014/15896391/658e8c66-2d90-11e6-9b4b-4774234637b7.png">

---

<img width="1280" alt="screen shot 2016-06-08 at 15 42 14" src="https://cloud.githubusercontent.com/assets/18290014/15896393/6598f99e-2d90-11e6-9db9-7871c7ce4bdc.png">

---

<img width="1280" alt="screen shot 2016-06-08 at 15 42 41" src="https://cloud.githubusercontent.com/assets/18290014/15896392/65923abe-2d90-11e6-92c6-60d73b28d11e.png">

**Comment by ThomasKerman** [comment]
Not exactly sure, but have you tried the Mod ID? (from the URL to the mod site)

**Comment by Cy4nX** [comment]
So, the 408 from http://spacedock.info/mod/408/Astroniki%20Sunflare%20for%20Scatterer?

Because that didn't work either.

**Comment by OzfurAtlas** [comment]
same problem with me. It just really sucks having to download 50+ mods individualy

**Comment by qhenckel** [comment]
I am getting the same problem.  I get this error in the javascript console when I click "edit pack"  
`Uncaught ReferenceError: Editor is not defined
    at edit_pack.js:10
    at edit_pack.js:167`

**Comment by LegoCollecter14** [comment]
I too am having this issue

**Comment by HebaruSan** [comment]
It looks like the mod selection functionality is **very** heavily dependent on the dropdown.

1. Start typing the name of the mod
2. **Wait** till a dropdown list of mods appears under the entry field
   ![image](https://user-images.githubusercontent.com/1559108/83319238-3c170f80-a202-11ea-8a33-a5fb5c538307.png)
3. Select the right one from the list
4. **Now** click Add Mod
5. Repeat if you like
6. Click Save Changes

Pasting the mod name or any other flow that doesn't involve clicking in the dropdown will probably always fail.

The Add Mod button does nothing if `new_mod` isn't set:

https://github.com/KSP-SpaceDock/SpaceDock/blob/e91894465c3a2885531355b9c813493ad93eaca4/frontend/coffee/edit_pack.coffee#L59-L63

And it's **only** set by the user making a selection in the type-ahead:

https://github.com/KSP-SpaceDock/SpaceDock/blob/e91894465c3a2885531355b9c813493ad93eaca4/frontend/coffee/edit_pack.coffee#L51-L57
