### ISSUE TITLE
Mod downloads are hit-and-miss

### ISSUE THREAD

**Issue by gerusz** [KSP-SpaceDock/SpaceDock#159]
Description (What went wrong?):

When downloading KSP mods, several files return with a 404. For example, Universal Storage 1.1.0.13. Others download without problem, for example. Universal Storage 1.1.0.12. This is completely independent of browser.

It also happens with plenty of other mods, and so far I couldn't find any rhyme or reason. [Planet Wiki](http://spacedock.info/mod/780/Planet%20Wiki) fails, for example, while [Probes Plus!](http://spacedock.info/mod/768/ProbesPlus%21) works.

Reproduction Steps (What did you do?):

A) I went to http://spacedock.info/mod/329/Universal%20Storage and clicked on "Download".

B) I typed "mono ckan.exe upgrade all" into a terminal.

Expected Behavior (What do you think should have happened instead?):

A) The Zip should have started downloading.

B) CKAN should have downloaded and updated the mod.

Environment (OS/Browser/Plugins/etc):

Primarily OSX / CKAN. Also tested: OSX / Chrome / lots of plugins, OSX / Firefox / no plugins, and OSX / Chrome, Dev Http Client app.

Location: The Netherlands. Might be relevant for the CDN, which I suspect is at fault here.

Extra Information (Screenshots/Error Messages/Javascript Console Output):

![screenshot 2016-06-21 19 56 12](https://cloud.githubusercontent.com/assets/658357/16240611/4f58dd34-37ea-11e6-9b29-bced56afdd69.png)

**Comment by DasSkelett** [comment]
Can't reproduce this, tested `Universal Storage 1.1.0.13`.
If you still encounter this problem, please re-open.
