### ISSUE TITLE
Refactoring the codebase into SpaceDock "branding"

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#16]
To achieve as clean a change over as possible, we should refactor the KerbalStuff modules / classes into SpaceDock references. It is **much** less confusing to work with the code base that way.

**Comment by EIREXE** [comment]
Not really, it's a completely unecessary change that could bring issues in the future.

**Comment by EIREXE** [comment]
It will also surely break the ability to grab code from other forks, so I would suggest against it.

**Comment by GenPage** [comment]
It's definitely an option, as we refactor code and develop new modules. I don't think its necessary to refactor all the modules and classes immediately, but definitely something to consider as we continue development

**Comment by phmayo** [comment]
Especially since @ThomasKerman is developing the KS codebase into something more configurable.

So, the real question is: Whither KerbalStuff's codebase? Do we want to develop for just the special case of KSP, or the more general case of mod hosting (with an eye to the KSP community's needs first)?

**Comment by EIREXE** [comment]
@phmayo keeping the naming is a better plan, as people can then incorporate stuff from this into kerbalstuff forks.

**Comment by phmayo** [comment]
Well, do we care about that? We **do** have a chance to have breaking changes, and develop this further than it is right now.

**Comment by ThomasKerman** [comment]
The KerbalStuff core libraries should stay named KerbalStuff, but I suggest that we put new classes and modules we develop under the SpaceDock name. This will make clear that the code is not KS, and we will maintain compatibility to other forks

**Comment by EIREXE** [comment]
@ThomasKerman Second this, it's retarded just to change it for no reason IMO.
