### ISSUE TITLE
Feature Request: Dont hide KSP version OnMouseOver

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#162]
Please, Dont hide KSP version OnMouseOver
![sd](https://cloud.githubusercontent.com/assets/560329/16488189/57136b52-3e9d-11e6-938c-573156673a99.png)

**Comment by HebaruSan** [comment]
Why? Need to know the reason to decide whether to do this, so we can compare the pros and cons with other approaches. Unfortunately this person deleted their GitHub account.

Closing as outdated and incomplete. If someone wants this and can make a case for it, we can re-open this.
