### ISSUE TITLE
Please change the default icon/thumbnail

### ISSUE THREAD

**Issue by t3pfaffe** [KSP-SpaceDock/SpaceDock#165]
I know not much of a "problem" but god it is so ugly and makes it look so bad. It is all pixelated and i feel a better looking one would make it 10x better. sorry for putting a non-real issue in issues, Just voicing a concern.

For further clarification:
/static/background-s.jpg

**Comment by HebaruSan** [comment]
Crafted by @V1TA5 based on team discussions:

![thumb](https://user-images.githubusercontent.com/1559108/117058839-ba1e4900-ace4-11eb-9f59-7a877ca2b94c.png)
