### ISSUE TITLE
website not loading

### ISSUE THREAD

**Issue by thatguycalledbinks** [KSP-SpaceDock/SpaceDock#167]
Description (What went wrong?): website not loading from google, history or typing web address in

Reproduction Steps (What did you do?): tried loading from google and typing in address manually

Expected Behavior (What do you think should have happened instead?): the site should load

Environment (OS/Browser/Plugins/etc): Opera (latest version)

Extra Information (Screenshots/Error Messages/Javascript Console Output):

**Comment by DasSkelett** [comment]
This issue is now four years old, it's probably no longer the case.
If it is, please open a new one.
