### ISSUE TITLE
Login changes protocol to unencrypted

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#168]
Description (What went wrong?):
Logging in at https://spacedock.info/* redirects to http://spacedock.info/*

Reproduction Steps (What did you do?):
- Go to https://spacedock.info/, optionally any of the "subdocks" ( ./kerbal-space-program/, ./factorio/, etc.)
- log in with an existing account

Expected Behavior (What do you think should have happened instead?):
After logging in, the protocol should remain the same.

If logging in via http (seriously? consider using a different browser...), landing page should be unencrypted as well, assuming the browser doesn't support encryption.
If using https, landing page should _not_ drop to http.

**Comment by allista** [comment]
Cannot reproduce this at the moment. Please confirm you still have this issue.

**Comment by V1TA5** [comment]
Should be autofixed by rev proxy auto upgrading to https again (and the webserver only doing http unlike before).
