### ISSUE TITLE
Exclude "new" mods, from being displayed in the "Recently Updated" list

### ISSUE THREAD

**Issue by StoneBlue** [KSP-SpaceDock/SpaceDock#170]
So keep "New" mods ONLY being shown under "New Mods", for the initial release...

Only allow mods to show in "Recently Updated mods", for second and subsequent releases... ie "updates"

This would keep "Recently Updated" from basically being redudndant and showing all the "new" mods... 
Also, it would allow recently updated mods to stay near the top of THAT list, longer, hopefully getting more visibility...

**Comment by HebaruSan** [comment]
Note, "exclude" isn't on the table because both lists include **all** mods. The difference is just which sort is applied, so this would amount to sorting mods with only one ModVersion to the end of the "recently updated" list.

**Comment by HebaruSan** [comment]
Recently Updated list is generated here for the index page:

https://github.com/KSP-SpaceDock/SpaceDock/blob/fa3926074da96180f7c75895a945b33c8e789744/KerbalStuff/blueprints/anonymous.py#L34-L35

And here for the full list:

https://github.com/KSP-SpaceDock/SpaceDock/blob/fa3926074da96180f7c75895a945b33c8e789744/KerbalStuff/blueprints/anonymous.py#L188-L189

Oddly, the `ModVersion.query.filter(ModVersion.mod_id == Mod.id).count() > 1` piece looks like we are already trying to exclude mods with only one version, so this may be as simple as figuring out why that doesn't work and fixing it.

Confirming that it definitely doesn't work:

![image](https://user-images.githubusercontent.com/1559108/96311996-4cbcfc00-0fd0-11eb-9d33-86c9e05a4e22.png)

https://spacedock.info/mod/2544/Restock%20MK1-3%20re-adder
![image](https://user-images.githubusercontent.com/1559108/96312035-652d1680-0fd0-11eb-812f-d52f2caca0ec.png)
