### ISSUE TITLE
Have mods show in "Recently Updated", when ONLY the KSP game vers has been updated, as well

### ISSUE THREAD

**Issue by StoneBlue** [KSP-SpaceDock/SpaceDock#171]
So mod devs have always been able to just update KSP version number, and NOTHING else, when the mod is compatable with NO changes required, for a new KSP version release.

However, after 1.2.1 dropped, it seems LOTS of devs have only edited KSP version number from 1.2, and made NO other changes...

The list seems to be generated by time/date stamp ONLY...
Basically, I am asking for a change in KSP game version to be considered also, in case it ALONE is changed, WITHOUT a new upload, or time/date stamp change.

So now if users want to shop for updated mods via the "Recently Updated" thumbnail page, all those recently "updated" mods for the new KSP version, will be mixed with all those that have NOT been changed, requiring longer searches, and page browsing further and further back in the list.
Technically, for a user to ensure they have the LATEST 1.2.1 versions of every mod on SD, they would have to browse all the way back to the release date of the PREVIOUS KSP release date... ie in this case, 1.2

**Comment by Joshwoo70** [comment]
why the caps? we can perfectly read it....

**Comment by StoneBlue** [comment]
Sorrr-yyy.. I sometimes use caps for emphasis, since tone cant be conveyed over the innerwebs via text

**Comment by DasSkelett** [comment]
Done in #279
