### ISSUE TITLE
Any way to keep downloads stat from increasing on canceled download?

### ISSUE THREAD

**Issue by StoneBlue** [KSP-SpaceDock/SpaceDock#173]
Download statistic updates when user clicks download button, but hits "cancel" button on the popup window, cancelling the download.

I apologize if theres no way to change this, I'm no programmer...

Just thought I would point it out, since it can falsely inflate a listed mods' statistics.

**Comment by HebaruSan** [comment]
No, I don't think this is possible. The backend just _starts_ the download and has no idea when or whether it finishes. Most of the time the download comes from the traffic server, so there's no way the backend could find out about it.
