### ISSUE TITLE
404 errors being experienced by users attempting download

### ISSUE THREAD

**Issue by SpannerMonkey** [KSP-SpaceDock/SpaceDock#175]
I have placed SpaceDock links for the recently created KSP mod,  SM Stryker,  on KSP  forums but although the links work perfectly for me they produce 404 errors for a lot/most of potential users.  

Reproduction Steps (What did you do?):
I've a feeling I may have accidentally created the problem though, when i was uploading the mod and creating the page , somehow I created two identical mods.
This didn't show up initially and it was only later in the day that I noticed the dupe.  I deleted 1 of the mods and remade all the links to the correct still existing version.

ALL os affected as far as I can tell

Links 
[SpaceDock](https://spacedock.info/mod/1197)

forum thread
[http://forum.kerbalspaceprogram.com/index.php?/topic/155996-122-sm_stryker-strykers-aerospace-and-armory-continued-by-sm/](url)

**Comment by StollD** [comment]
Try to upload the .zip file again, and create a new version. Deleting one of the duplicated mods deleted its zip file, which could've been referenced by both mods (that means the second mod tries to access a file that doesnt exist anymore)

**Comment by SpannerMonkey** [comment]
Hi
I'll give that a try now and report back

**Comment by SpannerMonkey** [comment]
Hi that seemed to work based on the way the downloads have increased, not had any mention of broken links for a few days so I'll consider this sorted for now and close the Issue
 Thanks for the tip
