### ISSUE TITLE
Seemingly not docking with stations

### ISSUE THREAD

**Issue by gappleto97** [KSP-SpaceDock/SpaceDock#176]
Description (What went wrong?):

When tracking the station, large numbers of NullPointerExceptions show up, the vessel is not docked to the station, and all crew assigned to the vessel are marked dead.

Reproduction Steps (What did you do?):

Sent up generic ships to dock with a simple station, consisting of girders and fuel tanks

Expected Behavior (What do you think should have happened instead?):

The ship should have arrived, the crew should not have died

Environment (OS/Browser/Plugins/etc):

Kubuntu 16.10. [modlist.ckan](https://github.com/KSP-SpaceDock/SpaceDock/files/851686/modlist.txt)

**Comment by StollD** [comment]
I think you took a wrong turn somewhere. Please read the Readme about the project before posting issues.

**Comment by gappleto97** [comment]
I did. The mod listed this page as source code. That, or I misread somewhere.

My apologies.
