### ISSUE TITLE
Cannot delete SVE from Spacedock

### ISSUE THREAD

**Issue by Nhawks1717** [KSP-SpaceDock/SpaceDock#177]
Description (What went wrong?):
I've been trying to delete [SVE](https://spacedock.info/mod/58/Stock%20Visual%20Enhancements) on Spacedock for awhile now and whenever I try to do it it just gives me an infinite load page and eventually times out.

Reproduction Steps (What did you do?):
Hit the delete button :P 

Expected Behavior (What do you think should have happened instead?):
Delete the mod from Spacedock

Environment (OS/Browser/Plugins/etc):
Chrome on Mac and PC both with no luck

Extra Information (Screenshots/Error Messages/Javascript Console Output):
If you want to just straight up delete the mod yourselves that's fine. I just want it removed from the site :P

**Comment by V1TA5** [comment]
I did unpublish it for you (Just because). Dont know why it couldnt be deleted. I deleted mods in the past.

**Comment by Nhawks1717** [comment]
Thanks for that! I don't know what happened either, it did that awhile back and I forgot to poke one of you guys about it then. Thanks for your help!
