### ISSUE TITLE
Email, Auth, and Sanity

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#18]
Thomas fixes the email auth problem *for now* to get SpaceDock up and running.

After this: refactor the email BS into something resembling sanity and working in a dev environment, so we don't have to fix in production.

**Comment by ThomasKerman** [comment]
Fixed this with glue in #19 

I will leave this opened since we don't have archived the full goal yet.

**Comment by ThomasKerman** [comment]
Closing this since the options returned in some pull request
