### ISSUE TITLE
[Improvement] Download counters by version (not by day) in the "Stats" tab

### ISSUE THREAD

**Issue by yalov** [KSP-SpaceDock/SpaceDock#185]
Download counters by version in the "Stats" tab

**Comment by V1TA5** [comment]
Im using Matomo/piwik for stats.
We can maaybe use it as source for stats (it needs to get numbers of direct file downloads via ckan/direct link).

**Comment by RockyTV** [comment]
Why not have both charts in the page? The current chart displays how many times a version was downloaded each day. We could just add another chart that displays how many times a version was downloaded since its release.

**Comment by HebaruSan** [comment]
One wrinkle here, the totals are calculated on the client (!), and the server only sends back 30 days worth of data (!!), so some refactoring will be needed to avoid displaying incomplete totals.
