### ISSUE TITLE
API: 401 on getting mod

### ISSUE THREAD

**Issue by ihsoft** [KSP-SpaceDock/SpaceDock#186]
If the mod is not published it cannot be fetched via `/api/mod/{mod_id}` even when authorized as the mod owner. The response is `401 - unauthorized`. This is quite inconvenient since when one is setting up an automation, the tests are done against the unpublished mods.

**Comment by V1TA5** [comment]
Hi,
sorry for that Bug.
Sadly there hasnt been any development on the Site for some Time now.
You dont (by any chance) know how to fix it?

**Comment by ihsoft** [comment]
I've send a PR. However, I didn't test it.
