### ISSUE TITLE
Did SpaceDock's GitHub CKAN user disappear?

### ISSUE THREAD

**Issue by HebaruSan** [KSP-SpaceDock/SpaceDock#188]
## Description

I think SpaceDock's CKAN checkbox is broken. We last received a pull request from SpaceDock in late May 2018; see this commit:

- https://github.com/KSP-CKAN/NetKAN/commit/b500ee50dec4031918842ebf8e5aade747aec970

![image](https://user-images.githubusercontent.com/1559108/43039114-39deb4be-8d16-11e8-8013-ee7dab222ba4.png)

However, if you click on that commit's associated pull request, it doesn't seem to exist:

- https://github.com/KSP-CKAN/NetKAN/pull/6571

![image](https://user-images.githubusercontent.com/1559108/43039148-e7feda74-8d16-11e8-8c0a-c8b044850971.png)

I think those pull requests used to be created by a GitHub user called `Space-Duck`? Who no longer exists? I hesitated to report this for a long time because I didn't know and couldn't find the official team history of it, but it's been quite a while since we've heard from SpaceDock's bot, so it's probably worth looking into.

Please let us know if there's any info we can provide or anything we can do to help!

**Comment by HebaruSan** [comment]
Do you happen to know who created the Space-Duck user (i.e., was it someone from SpaceDock or CKAN)? Maybe GitHub auto-deleted it because of some rule about how bot accounts should be set up.

Are there logfiles that could confirm that SpaceDock is still trying to create pull requests? There might be an error message that could indicate what happened.

**Comment by StollD** [comment]
I created it, but I don't know which email I used anymore (might be a virtual mail address that redirected to VITAS mail account, or support@spacedock.info), so even if there is a notification, I don't know where it ended up.

**Comment by V1TA5** [comment]
Hi,
now i remember. Service@spacedock.info terminates to otrs on my server (i think you Thomas should have acc to that if not ping me)

The server is running notify, mail and spacedock itself and it seems to send mails and notify (i can past logs if need be).

Im planing to move all the things for some time now and i still want to but atm its still where it always was.

I hope that helps.

**Comment by HebaruSan** [comment]
Oh wow we just got a backlog of **125** previously hidden pull requests! Looks like Space-Duck is back in business! Thanks for fixing this.
https://github.com/issues?q=is%3Apr+is%3Aopen+author%3ASpace-Duck
