### ISSUE TITLE
The unpublished mods are visible to the public

### ISSUE THREAD

**Issue by ihsoft** [KSP-SpaceDock/SpaceDock#189]
Steps to reproduce:
* Create an unpublished mod.
* Go to the author's page.

Observed result:
* The unpublished mod is visible in the "Mods by \<username\>" section.
* When clicked on the mod, the result is "Unauthorized", which is the right behavior.

Expected result:
* The unpublished mod must only be visible to the owner.

**Comment by RockyTV** [comment]
Closed by #229 - issue was present on frontend but isn't present on backend.
