### ISSUE TITLE
Sort mods by version number

### ISSUE THREAD

**Issue by Cataclysmm** [KSP-SpaceDock/SpaceDock#191]
Description (What went wrong?): It's become increasingly difficult to sort thu the dozens of pages to look for modules made for a specific game version, i.e 1.3.1, or 1.51 A mistake can mean hours trying one module at a time to find the bad seed. Add a filter by version number displayed in upper corner of thumbnails.

Reproduction Steps (What did you do?): change any page

Expected Behavior (What do you think should have happened instead?): Click and only view those modules that will work with the version of the game you wish to play.

Environment (OS/Browser/Plugins/etc):Chrome

Extra Information (Screenshots/Error Messages/Javascript Console Output):

**Comment by RockyTV** [comment]
Just type `ver:1.5.1` in the search box. Although the current website is buggy but working, these features do exist.

In case you're wondering, we're still looking for help to get the new code base up. Specifically, we are looking for help to [port the old theme](https://github.com/KSP-SpaceDock/OpenDock) to the new code base.

**Comment by Cataclysmm** [comment]
Thanks, I tried many searches to no avail.
