### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by RiktaD** [KSP-SpaceDock/SpaceDock#194]
#### Description (What went wrong?):

The Certificate has expired some hours ago.
Therefore no secure connection can be established.

#### Reproduction Steps (What did you do?):

Visit the Site with a proper browser
`- or -`
Install something via ckan

#### Expected Behavior (What do you think should have happened instead?):

Working https-connection.

#### Environment (OS/Browser/Plugins/etc):

It's a Backend-Bug totally unrelated to my system.
But a Linux Mint 19, Vivaldi Browser / CKAN

#### Extra Information (Screenshots/Error Messages/Javascript Console Output):

Well, I assumed the title would have been already enough information :)

**Comment by Lartza** [comment]
I've pinged @V1TA5 on IRC already an hour ago, waiting on a response but then it'll hopefully be fixed ASAP. Issue hopefully directs everyone here instead of opening new ones :)

**Comment by RiktaD** [comment]
Closed as the Certificate is renewed and working again.
