### ISSUE TITLE
"Markdown" link opens in same window

### ISSUE THREAD

**Issue by mwerle** [KSP-SpaceDock/SpaceDock#196]
Description (What went wrong?):
While editing mod description, I needed to look up some Markdown syntax.  Clicking on the link opened the Markdown page, making me lose all my work.

Reproduction Steps (What did you do?):
Log in, Edit mod.

Make some changes to mod description.

Click on "Markdown" link.

Note loss of work as "Markdown" link is opened in same window with no warning.

Expected Behavior (What do you think should have happened instead?):
Link should either issue warning, open in a pop-up, or open in a new Windows or Tab.

Environment (OS/Browser/Plugins/etc):
Windows/Chrome

Extra Information (Screenshots/Error Messages/Javascript Console Output):

**Comment by mwerle** [comment]
PS. I know there's a UX-guideline against opening links in new windows and instead letting the user decide, however in situations where loss-of-work is a possibility I think there's an argument for going against that guideline.

Besides which, some of the pages on Spacedock already opened the Markdown link in a new page/tab.  This just makes it consistent.

**Comment by HebaruSan** [comment]
Fixed in #197.
