### ISSUE TITLE
More configuration options

### ISSUE THREAD

**Issue by StollD** [KSP-SpaceDock/SpaceDock#2]
Site name, source code adress and support email should be configurable without editing the template files. 

We probably want to put everything into config.ini, since it is there, it is dynamic (which is good) and it is .ini, which is easy to parse and to read. That results in a faster startup.

**Comment by riverajo** [comment]
Subreddit lurker looking to help out, I was taking a look at the project and it looks like the options you mention have already been moved to the .ini. If you could gather up any more options you think would be good to move I could take a stab at it.

Also while poking around with configuration I noticed that there appears to be 2 config.py modules, one in the KerbalStuff directory and one in the root level. The one one in the root level appears to be a vestige of the original work but doesn't appear to be used anywhere, can you confirm?

**Comment by DasSkelett** [comment]
A lot of "static variables" (ha!) are now configured in the `config.ini`.
The second `config.py` also seems to be gone.
