### ISSUE TITLE
Upload hangs at 100% for 9 hours+

### ISSUE THREAD

**Issue by GregroxMun** [KSP-SpaceDock/SpaceDock#208]
Description:

I uploaded my latest patch to Whirligig World, 0.10.3, which can be found [here](https://github.com/GregroxMun/Whirligig-World/releases/tag/0.10.3). Upon hitting the publish release button, the upload progress bar progresses at a normal speed, before reaching 100%, and then nothing happens. I tried once and let it go for around 20 minutes before reloading and trying again. This time I left it over night. When I woke up it was still hanging at 100%. I reloaded and attempted once more this morning and it still stops.

Reproduction Steps:

I uploaded the .zip file with the changelog, both the file and text are identical on the GitHub repository listed above, set the update name, and hit publish.

Expected Behavior:

Upon reaching 100%, I'd expect it to linger for *maybe* a minute, and then the page would reload and the mod will be updated.

Environment:

Chrome on Windows 10. Only custom extensions are AdBlock and Wolfram|Alpha.

Extra Information (Screenshots/Error Messages/Javascript Console Output):

I'm not sure exactly what to do here, but I did open the F11 menu and there was the following errors:

Failed to load resource: the server responded with a status of 500 ()    
update:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0    
    at JSON.parse (<anonymous>)    
    at XMLHttpRequest.xhr.onload (update.js:64)

**Comment by V1TA5** [comment]
Hi im on it.

**Comment by V1TA5** [comment]
Fixed.
The mod storage is mounted via SMB and somehow went into Readonly mode.
I remember having a similar problem with nfs 2 years ago. It fixed itself trough rebooting the server but finding the cause will still be a task.
I hope we can figure that one out before it hangs again.
Please inform me if it happens again.
(We are also on irc (#spacedock on espernet), Discord (cant remember the server atm) and matrix (+spacedock:52k.de on im.52k.de) if you like to join us and help with the site.
