### ISSUE TITLE
Fix / add admin Panel

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#210]
The Admin panel i started isnt finished and also freezes the browser due to trying to load all data at once.
It could also use some more functions.

**Comment by allista** [comment]
Don't we want to use flask-admin for this? It gives plenty out of the box and is easily customizable.

**Comment by V1TA5** [comment]
Im ok with whatever enables us to have this. Im also ok with removing my attempt compleatly.

**Comment by HebaruSan** [comment]
Fixed in #262.
