### ISSUE TITLE
Add Delete Account Option

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#215]
Add Option for users to delete their own Account.

**Comment by RockyTV** [comment]
Should the user mods be deleted when they request the deletion of their account? Or should we leave it up but add a special tag to the mod?

**Comment by techman83** [comment]
Depends on how the mod is licensed. If it's not an Open Source license, I think you would be compelled to.

All the open source mods do get mirrored automatically on Archive.org.

**Comment by RockyTV** [comment]
@techman83 How do you detect if a mod is open source?

**Comment by HebaruSan** [comment]
> @techman83 How do you detect if a mod is open source?

It's based on the license:

https://github.com/KSP-CKAN/NetKAN-bot/blob/4f218a2085f9a5e49f151c499a9192e97c5af728/lib/App/KSP_CKAN/Metadata/Ckan.pm#L211-L218

https://github.com/KSP-CKAN/NetKAN-bot/blob/4f218a2085f9a5e49f151c499a9192e97c5af728/lib/App/KSP_CKAN/Roles/Licenses.pm#L125-L157
