### ISSUE TITLE
Main View align logged in & logged out 

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#216]
Same Index layout for loged in as well as loged out users (they dont need to differ)

**Comment by HebaruSan** [comment]
### Logged out

- Featured
- Newest
- Recently Updated
- Most Popular
- Packs

### Logged in

- Followed
- Featured
- Newest
- All
- Recently Updated, Popular, Packs

### Proposed unified end state

- Followed (if logged in)
- Featured
- Newest
- Recently Updated
- All/Popular (these are the same thing)
- Packs
