### ISSUE TITLE
Ability to post changelogs

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#218]
Ability for mod authors to post changelogs along with their mod version releases (like mod description as markdown)

**Comment by allista** [comment]
What's the difference with current release description? Everyone uses it for that purpose anyway

**Comment by V1TA5** [comment]
We could rename it.

I want to encurage mod authors to post chnagelogs in the usual styles
(fixes, features,...).

(We could have the same for gameversions at some point)

**Comment by HebaruSan** [comment]
This is already supported, and authors are using it.

![image](https://user-images.githubusercontent.com/1559108/86278822-9b1fc980-bb9e-11ea-87b8-d7e682dda570.png)
