### ISSUE TITLE
Storage Drive goes to read-only, mod uploads and updates do not work. 

### ISSUE THREAD

**Issue by GregroxMun** [KSP-SpaceDock/SpaceDock#226]
The last time I had this issue, it had been fixed, but it seems to be back again. https://github.com/KSP-SpaceDock/SpaceDock/issues/208#event-2531707826

I was updating Alternis Kerbol Rekerjiggered, and just as last time, hitting the publish release button, the upload progress bar progresses at a normal speed, before reaching 100%, and then nothing happens.

**Comment by DasSkelett** [comment]
> I hope we can figure that one out before it hangs again.

There goes the hope...

**Comment by DasSkelett** [comment]
Temporarily fixed again.
Until we find a solution to the underlying problem (which is also still unknown), this might occur a few more times.

**Comment by V1TA5** [comment]
The Enviroment: Proxmox with mounted smb share as "Storage". Virtual Drive is mounted into lxc container on this storage for mod files. Worked for month. After updating the server it starts to go read only after a week or two. 
I had this 2-3 years ago with nfs mounts on another share on the same storage.
Never solved it.
I will ask the DC for advice.

**Comment by HebaruSan** [comment]
I believe some work was done on this over the last couple of updates. @DasSkelett and/or @V1TA5, does it seem to be solved now?

**Comment by HebaruSan** [comment]
The site's recent stability suggests that the infrastructure work has resolved this. Let's re-open it if it starts happening again.
