### ISSUE TITLE
Creating mods via API needs game id

### ISSUE THREAD

**Issue by DasSkelett** [KSP-SpaceDock/SpaceDock#227]
Description (What went wrong?):
---
Creating a new mod via the API doesn't work:
```html
<html>
	<head>
		<title>Internal Server Error</title>
	</head>
	<body>
		<h1><p>Internal Server Error</p></h1>
	</body>
</html>
```

Reproduction Steps (What did you do?):
---
```sh
curl -c ./cookies -b ./cookies \
    -F "name=test" \
    -F "short-description=temp" \
    -F "version=1.0" \
    -F "game-version=1.7.3" \
    -F "license=MIT" \
    -F "zipball=@sd-test.zip" \
    -F "game=kerbal-space-program" \
    "https://spacedock.info/api/mod/create"
```

Expected Behavior (What do you think should have happened instead?):
---
API returns something along the lines of:
```json
{
  "url": "/mod/XXXX/test"
}
```

Environment (OS/Browser/Plugins/etc):
---
Linux/Kubuntu 19.04, curl 7.64.0

Extra Information (Screenshots/Error Messages/Javascript Console Output):
Creating a new mod via the website works, if #226 is not striking currently.
Updating mods via the API works too.

**Comment by RockyTV** [comment]
It doesn't work because `game` expects an int, not a string: https://github.com/KSP-SpaceDock/SpaceDock/blob/alpha/KerbalStuff/blueprints/api.py#L575

**Comment by DasSkelett** [comment]
So the game id. No way we can expect an uploader to know it.
The API should be extended to also search whether the provided string/int matches any `game.name`, `game.altname` or `game.short`.

**Comment by RockyTV** [comment]
I suggest we implement a function that queries for short name, name or game id, depending on the type of the parameter passed to the function. Something like this: https://github.com/KSP-SpaceDock/SpaceDock-Backend/blob/python/SpaceDock/objects.py#L184

**Comment by HebaruSan** [comment]
> So the game id. No way we can expect an uploader to know it.

In theory, the uploader can get the game ID from https://alpha.spacedock.info/api/games , although that crashes on production.

**Comment by DasSkelett** [comment]
> > So the game id. No way we can expect an uploader to know it.
> 
> In theory, the uploader can get the game ID from [alpha.spacedock.info/api/games](https://alpha.spacedock.info/api/games) , although that crashes on production.

At least something. But I still see sense in implementing something like @RockyTV suggested. Doesn't cost much, and is quite useful.

**Comment by allista** [comment]
Don't agree with the proposal. API should be strict about the types attributes.
If we don't want to impose on a client the need to know internal game IDs, we should just change the meaning of the corresponding API call argument from `id` to `short`. No need to guess as to what the client meant by ID.

**Comment by DasSkelett** [comment]
I'm open for that too. I don't know API best practices, but being strict sounds reasonable.
Main point is that there should be a way to specify the game by a better know string.

**Comment by HebaruSan** [comment]
This was fixed, but GitHub got confused.
