### ISSUE TITLE
Internal Server Error when accessing user profiles

### ISSUE THREAD

**Issue by RockyTV** [KSP-SpaceDock/SpaceDock#228]
**Description (What went wrong?):**
Some user profiles return Internal Server Error, with no custom style. Just a plain HTML header saying "Internal Server Error".

**Reproduction Steps (What did you do?):**,
I tried to create a mod for No Man's Sky, to test an old bug that unpublished mods are visible. After creating the mod, I couldn't view my profile and I couldn't publish the mod either.

Profile link: https://spacedock.info/profile/Xinayder

**Expected Behavior (What do you think should have happened instead?):**
Profile page should work.

**Environment (OS/Browser/Plugins/etc):**
- Firefox v68.0.1 (64-bit)
- Arch Linux, kernel 5.2.6-arch1-1-fsync
- uBlock Origin, HTTPS Everywhere, Privacy Badger (none interfere with SpaceDock)

**Extra Information (Screenshots/Error Messages/Javascript Console Output):**
Accessing the same page with a private tab has the same error, but with SpaceDock's styling.

**Comment by RockyTV** [comment]
I forgot to add to this issue, but the previous issue was caused by a mod not having a `default_version` field set.

**Comment by allista** [comment]
This should be fixed along with #227 when they fix my internet connection :persevere:

**Comment by HebaruSan** [comment]
This profile currently works fine in production.
