### ISSUE TITLE
Enhancement:CKAN Opt-In Page

### ISSUE THREAD

**Issue by inigmatus** [KSP-SpaceDock/SpaceDock#23]
I recommend moving the CKAN check box off the main mod upload submission form, and instead present authors a page asking if they'd like their mod to be included on CKAN, espousing its benefits with the opt-in being a button, and continue without opting-in another button, and a text explaining that a mod author can opt-in later or opt out later (if possible). 

Then the next page would be the form to upload their mod.

**Comment by ThomasKerman** [comment]
Closing this, since the CKAN checkbox is already opt-in and we don't need much more than the checkbox to support CKAN for the time being.

**Comment by inigmatus** [comment]
agreed.
