### ISSUE TITLE
Unable to upload image for banner of a mod pack

### ISSUE THREAD

**Issue by allista** [KSP-SpaceDock/SpaceDock#238]
When choosing to upload n image as a background for a mod pack, nothing happens. The text changes to "Uploading...", but nothing happens, no network traffic, no requests at all.

**Comment by HebaruSan** [comment]
Are you trying this on alpha? Recent uploads to production seem to have had no problem uploading backgrounds:

https://spacedock.info/mod/2212/Transparent%20Command%20Pods%20Repressurized%20

**Comment by allista** [comment]
Yea, on alpha. Didn't try on beta.

**Comment by HebaruSan** [comment]
OK, I think it's just something we haven't set up on alpha, rather than a bug.
