### ISSUE TITLE
No comments on blog posts

### ISSUE THREAD

**Issue by allista** [KSP-SpaceDock/SpaceDock#241]
It is said that comments are powered by something, but there's no way to actually live a comment.

https://alpha.spacedock.info/blog/1

**Comment by HebaruSan** [comment]
Looks like this is driven by a setting that isn't set.

https://github.com/KSP-SpaceDock/SpaceDock/blob/618c8716cf39b7326a472c403bd6ff55351bd5f9/KerbalStuff/app.py#L229

https://github.com/KSP-SpaceDock/SpaceDock/blob/618c8716cf39b7326a472c403bd6ff55351bd5f9/templates/disqus.html#L3-L8

![image](https://user-images.githubusercontent.com/1559108/85917180-91543a00-b81d-11ea-9e62-215d458389ff.png)

https://help.disqus.com/en/articles/1717082-what-is-a-disqus-identifier

Maybe @V1TA5 could set up an ID and then apply it in the config?

https://github.com/KSP-SpaceDock/SpaceDock/blob/618c8716cf39b7326a472c403bd6ff55351bd5f9/config.ini.example#L80-L81
