### ISSUE TITLE
Banner Image Upload is Loading Blank Image Instead

### ISSUE THREAD

**Issue by inigmatus** [KSP-SpaceDock/SpaceDock#25]
Image Uploading is not working. Currently loading blank image.

trying to save this to desktop and uploading to banner: http://i.imgur.com/BzOfrNN.png

**Comment by inigmatus** [comment]
http://i.imgur.com/BzOfrNN.png  is the image I'm attempting to upload from desktop.

**Comment by GenPage** [comment]
Console reports "https://spacedock.info/content/genpage-1455661575.5468342_183/genpage.jpg Failed to load resource: the server responded with a status of 404 (NOT FOUND)"

**Comment by Olympic1** [comment]
@RealKolago said:
> On the old KS site were mod title pictures uploaded by the mod creators. For the moment these are gone. But if you bring back these I have a suggestion:

> On KS these pictures were sometimes huge and take a long time to load.
To speed thinks up consider to scale same down to the size needed on the front page.
