### ISSUE TITLE
Request: Allow links to download always latest version

### ISSUE THREAD

**Issue by Monniasza** [KSP-SpaceDock/SpaceDock#251]
The "Download" button would direct to "latest" version - which changes dynamically.

Example: Mod A is version A at https://spacedock.info/mod/xxx/A
Download button creates https://spacedock.info/mod/xxx/A/download/A
Then author uploads Version B
Original link becomes outdated
Download button creates https://spacedock.info/mod/xxx/A/download/B

After update:
Example: Mod B is version A at https://spacedock.info/mod/yyy/B
Download button creates https://spacedock.info/mod/yyy/B/downloadlatest
Then author uploads Version B
Original link is still up to date
Download button creates https://spacedock.info/mod/yyy/B/downloadlatest

**Comment by DasSkelett** [comment]
I thought about this a bit and I'm wondering whether this should be a different API route as you suggested (`/mod/<int:mod_id>/<path:mod_name>/downloadlatest`),
or alternatively incorporated in `/mod/<int:mod_id>/<path:mod_name>/download/<version>` as special handling for `version == 'latest'`.
For the second one we would need to ensure that authors can't upload a version with the name `latest` (which would be a pretty dumb thing to do, but you never know...).

Both solutions would make sense (and would be rather easy to implement), I'd welcome some input from others what is the better design decision.

**Comment by HebaruSan** [comment]
Should it be the most recently uploaded version, or the `default_version` as chosen with the "Set as default" buttons?

![image](https://user-images.githubusercontent.com/1559108/85445121-a6e50d80-b558-11ea-9448-f0d0cdc05149.png)

As for the route syntax, I think we have an even easier option: Just omit the version part of the URL entirely.

- https://alpha.spacedock.info/mod/3/download

**Comment by DasSkelett** [comment]
It should be the `default_version` IMHO, which is the one that is downloaded with the big button. We could then also change the button over to that new route.
You route syntax would also solve the problem that `latest` might be confusing if it is not necessarily really the newest (even though it is in 99.9% of cases).

**Comment by Monniasza** [comment]
> Should it be the most recently uploaded version, or the `default_version` as chosen with the "Set as default" buttons?
> 
> ![image](https://user-images.githubusercontent.com/1559108/85445121-a6e50d80-b558-11ea-9448-f0d0cdc05149.png)
> 
> As for the route syntax, I think we have an even easier option: Just omit the version part of the URL entirely.
> 
> * https://alpha.spacedock.info/mod/3/download

It didn't download using only the link, but I agree with this syntax.

**Comment by HebaruSan** [comment]
> > * https://alpha.spacedock.info/mod/3/download
> 
> It didn't download using only the link, but I agree with this syntax.

I discovered a problem with that syntax, the format of the normal mod info HTML page is this:

> > * https://alpha.spacedock.info/mod/3/modname

So if a mod is named 'download', the URLs are the same and things break. SpaceDock needs to be able to tell the difference. I proposed a compromise in #289, hopefully it will work out.

**Comment by Monniasza** [comment]
> > > * https://alpha.spacedock.info/mod/3/download
> > 
> > 
> > It didn't download using only the link, but I agree with this syntax.
> 
> I discovered a problem with that syntax, the format of the normal mod info HTML page is this:
> 
> > > * https://alpha.spacedock.info/mod/3/modname
> 
> So if a mod is named 'download', the URLs are the same and things break. SpaceDock needs to be able to tell the difference. I proposed a compromise in #289, hopefully it will work out.

I'v e got 500 Internal Error for the new link.

**Comment by HebaruSan** [comment]
> It didn't download using only the link, but I agree with this syntax.

> I'v e got 500 Internal Error for the new link.

The new syntax is not live on the server yet. These are just examples.
