### ISSUE TITLE
http://spacedock.info should redirect to https://spacedock.info

### ISSUE THREAD

**Issue by gam3guy** [KSP-SpaceDock/SpaceDock#29]
Needs a redirect - to spacedock.info as shorter? also maybe force https

**Comment by GenPage** [comment]
Force HTTPS through Apache 301 redirect

**Comment by Electro-ninja** [comment]
Not a duplicate, they both lead to the same place, just a dns compatability thing.

**Comment by NecroBones** [comment]
301 redirect would be ideal so that Google results are consistent and the pagerank all counts toward the same URLs.

**Comment by TN-1** [comment]
Closed per #125
