### ISSUE TITLE
Making a Dockerfile for easy setup

### ISSUE THREAD

**Issue by ThomasKerman** [KSP-SpaceDock/SpaceDock#3]
Yeah, currently, the setup process is a painful mess, a dockerfile (or even just a simple build script) would be a good option to make this easier. Even though simple shell scripts would work too, a Dockerfile would be prefered since Docker takes care of everything needed in the background and you can easily start / stop the software.

I will look into this in the future, if someone voluteers, even better :)

**Comment by FrikFry** [comment]
Seems reasonable. I'm happy to look at this.

**Comment by phmayo** [comment]
What about Chef/Ansible/Capistrano/Puppet recipes? Good idea, bad idea, ignore?

**Comment by FrikFry** [comment]
No strong feelings either way. I'm personally most familiar with vagrant.

**Comment by FrikFry** [comment]
So I've poked this into reasonable shape. I seem to have everything but the redis/email stuff working out of the docker image. From the viewpoint of getting this working for development, I don't think that having redis/email working on the docker image is necessary. Anyone feel otherwise?

**Comment by GenPage** [comment]
I agree, you can pre-populate the DB for development to avoid needing the mailer. Some documentation on setting up the dev environment would be great
