### ISSUE TITLE
Thumbnails use png extension but are jpg

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#308]
The thumbnails are generated as jpg but saved with the png extention.

**Comment by HebaruSan** [comment]
Confirmation of created as jpg:

https://github.com/KSP-SpaceDock/SpaceDock/blob/c2ea90292d6810a730898120a5fe7bbe4b44d340/KerbalStuff/thumbnail.py#L12

The filename is in here somewhere:

https://github.com/KSP-SpaceDock/SpaceDock/blob/61175067b483e7eed5ba12e5d275c9dd51550b18/KerbalStuff/objects.py#L188-L191

I think it uses the same extension as the full size image.
