### ISSUE TITLE
Turn the ksp-game-id var into db flags

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#329]
Please turn the ksp-game-id var into db flags.
The code should be as game independent as possible. We don't want to crowd config.ini with game specific flags if possible.
(CKAN specific ones could be columns in the db table. Could also come in handy if they/you ever support other games too)

_Originally posted by @V1TA5 in https://github.com/KSP-SpaceDock/SpaceDock/pull/294#issuecomment-704061030_

**Comment by HebaruSan** [comment]
Fixed in #480.
