### ISSUE TITLE
BahamutoD has found a point of attack

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#35]
The JSON generated seems buggy. A locale or generation issue, maybe.

Screenshot: https://puu.sh/naE0e/98ccbf71fd.png

**Comment by phmayo** [comment]
An additional point of attack:

http://www.gossamer-threads.com/lists/apache/dev/420131

`SSLProxyCheckPeerCN` in the Apache conf could be at fault.

**Comment by FrikFry** [comment]
People can upload mods now, closing.
