### ISSUE TITLE
Mass mod upload

### ISSUE THREAD

**Issue by Shuudoushi** [KSP-SpaceDock/SpaceDock#38]
what's on the tin ^

**Comment by Shuudoushi** [comment]
I'll explain this idea a little. This mostly came to mind for people that have a crap ton of mods (blowfish, BD, LGG, ect.) that need to be uploaded. I suggest a 10 file limit (or something less insane).

**Comment by ThomasKerman** [comment]
I am against this, since that would still require the complete mod uploading page, and to be honest: It is not that hard to press two buttons after you published a mod to upload the next one.

Also, they could use the API to automate this process.
