### ISSUE TITLE
Gmail doesn't seemed to be receiving confirmation emails

### ISSUE THREAD

**Issue by ILM126** [KSP-SpaceDock/SpaceDock#41]
After almost 3-4 hours since I registered, no emails have been received. Not sure if Google is just blocking emails or if it is just the mail system being slow.

**Comment by beanjo55** [comment]
same issue here. Was not delivered or caught in spam filter

**Comment by ThaZeus** [comment]
I got my email and i use gmail so might be a localized problem.

**Comment by NecroBones** [comment]
It's more widespread than gmail. I run my own mailserver, and there's no sign of a delivery attempt from spacedock.

**Comment by inigmatus** [comment]
mta logs show delivery to google frontend servers, but my guess is google is silent discarding or spamming the messages. my full time job is email troubleshooting, so if i were to venture a professional guess, I would say that the reason is not passing on the emails on to inboxes is because the sending IP we're using is not established yet. It needs to build up reputation, and that could take a while... anywhere from 48 hours to two weeks.

**Comment by TN-1** [comment]
Closing because this isnt an issue on our end.

**Comment by jwolff52** [comment]
As per [this](https://support.google.com/mail/answer/81126#format). Could it be because we are not passing a Message-id? I know you just closed this, but I did some digging earlier and was about to see if someone had brought it up...

**Comment by TN-1** [comment]
@inigmatus would be the one to ask about that.

**Comment by inigmatus** [comment]
i can't reopen GH issues unfortunately

@ThomasKerman ideas?

**Comment by inigmatus** [comment]
check that. i can re-open.

**Comment by NecroBones** [comment]
Looking at those gmail bulk mail standards, and comparing against a message I received from SpaceDock already. 

Message ID looks OK to me, and is generally added by the MTA (mail transfer agent). What they recommend that's missing though, is the "Precedence: bulk" header field. That would need to be added in the same function as my current PR for #68 for dealing with the "To" field, just outside the loop where "From" (etc) is set.

**Comment by TN-1** [comment]
```
message['Subject'] = subject
message['From'] = sender
$headers .= 'Precedence: bulk'
      for group in chunks(recipients, 100):
         message['To'] = "undisclosed-recipients:;"
          print("Sending email from {} to {} recipients".format(sender, len(group)))
          smtp.sendmail(sender, group, message.as_string())
      smtp.quit()
```   
Would that be correct?
Been a while since I have worked with smtp servers

**Comment by jwolff52** [comment]
I believe it should be
    message['Precedence'] = 'bulk'
Or am I misunderstanding something?

**Comment by TN-1** [comment]
That sounds like it would be more likely, To be honest I just googled it. Haha

**Comment by jwolff52** [comment]
Lol I think what you had is php not python :P

**Comment by TN-1** [comment]
Eh same difference. :p

**Comment by jwolff52** [comment]
However, just thinking about it, do we want confirmation emails and the like to show up as bulk as well? Because all of the emails pass through this method. So perhaps we should check if

    recipients

Has more than one person in it and then set the precedence:

    if len(recipients) > 1
      message['Precedence'] = 'bulk'

**Comment by NecroBones** [comment]
That's a good idea. In fact, the change I was making to hide the "To" field could probably use the same if conditional. No need to hide the "To" if it's going to one person.

**Comment by jwolff52** [comment]
Very true, didn't even consider that as I was driving when I was typing that...don't text and drive kids.

**Comment by jwolff52** [comment]
So we end up with something along the lines of this perhaps?

    message = MIMEText(message)
    if important:
        message['X-MC-Important'] = "true"
    message['X-MC-PreserveRecipients'] = "false"
    message['Subject'] = subject
    message['From'] = sender
	type = 'To'
	if len(recipients) > 1:
	    message['Precedence'] = 'bulk'
		type = 'Bcc'
	
    for group in chunks(recipients, 100):
        message[type] = ";".join(group)
        print("Sending email from {} to {} recipients".format(sender, len(group)))
        smtp.sendmail(sender, group, message.as_string())
    smtp.quit()

**Comment by NecroBones** [comment]
I've updated my PR #82 to include this.

**Comment by jwolff52** [comment]
:+1:  Looks good to me, I forgot we don't have to add them to the Bcc field :P

**Comment by NecroBones** [comment]
Yup, BCC doesn't technically exist that way. ;)

**Comment by NecroBones** [comment]
What's funny is the code snippet you posted, I was in the middle of editing it myself at the same time. lol

**Comment by Orkeren** [comment]
Just an update on this. The email arrived just fine - almost instantly. But it ended in gmails spam-folder.

**Comment by NecroBones** [comment]
That's probably to be expected until we build up reputation.

**Comment by ILM126** [comment]
@Orkeren At least it's a start :grinning:

**Comment by plague006** [comment]
For what it's worth just created my account, received email within seconds and was in inbox. Congrats on not being spam?
