### ISSUE TITLE
Ability to filter results on API for a specific game

### ISSUE THREAD

**Issue by RedstoneWizard08** [KSP-SpaceDock/SpaceDock#465]
Description (What went wrong?):

I'm working on the installer for SpaceWarp over at https://github.com/SpaceWarpDev/Space-Warp-Installer and https://github.com/RedstoneWizard08/Space-Warp-Installer and I'm trying to filter mods on the API for only KSP2, but there is no option for that, and then the pagination breaks because it fetches all mods and some pages will be blank.

Reproduction Steps (What did you do?):

```ts
import axios from "axios";

import { finishBrowseResult } from "./models/browse";
import { finishFullModInfo } from "./models/modinfo/full";

export class SpaceDockAPI {
    private base: string;

    public constructor(baseUrl?: string) {
        this.base = baseUrl || SpaceDockAPI.getDefaultAPIUrl();
    }

    public static getDefaultAPIUrl() {
        return "https://spacedock.info/api";
    }

    public async getMods() {
        const response = await axios.get(`${this.base}/browse`);
        
        return finishBrowseResult(response.data);
    }

    public async getMod(id: string | number) {
        const response = await axios.get(`${this.base}/mod/${id}`);

        return finishFullModInfo(response.data);
    }

    // example: getModsForGame(22407) = KSP2
    public async getModsForGame(gameId: number) {
        const response = await this.getMods();
        const mods = response.result.filter((mod) => mod.game_id == gameId);

        return mods;
    }
}
```

Expected Behavior (What do you think should have happened instead?):

What I would like is to be able to filter on the browse API with more parameters like `game_id` and `game_version` to allow for easier use.

Environment (OS/Browser/Plugins/etc):

1. Windows/Wry (Tauri)/Tauri/Preact/TypeScript
2. Chrome OS/Chrome/Preact/Vite/TypeScript
3. Linux (Ubuntu 22.04)/TypeScript

Extra Information (Screenshots/Error Messages/Javascript Console Output):

**Comment by HebaruSan** [comment]
The `/api/browse` route is here if you want to try adding the filters you need:

https://github.com/KSP-SpaceDock/SpaceDock/blob/dbd67221961376193983028c8977c51b5296204d/KerbalStuff/blueprints/api.py#L302-L343

SpaceDock is open source and pull requests are welcome. If you do, please target the `alpha` branch as that's where [SpaceDock's dev process](https://github.com/KSP-SpaceDock/SpaceDock/wiki/Development-Guide) starts.

**Comment by RedstoneWizard08** [comment]
I'll give it a try!

**Comment by HebaruSan** [comment]
That dev guide link also has a section on starting an instance of SpaceDock locally in Docker, which is _extremely_ helpful for debugging (but may be overkill for a relatively small API change):

https://github.com/KSP-SpaceDock/SpaceDock/wiki/Development-Guide#running-with-docker

**Comment by RedstoneWizard08** [comment]
I was already doing that lol but yea I'm gonna do dev in docker. Is there like an alpha preview deployed btw so I could use it sooner, before it goes into the stable release?

**Comment by V1TA5** [comment]
https://alpha.spacedock.info/
For compleatness beta also exists for later testing:
https://beta.spacedock.info/

**Comment by HebaruSan** [comment]
No, but there's an alpha server with a separate database:

https://alpha.spacedock.info/

Useful for public testing but not for accessing data from the production server.

**Comment by RedstoneWizard08** [comment]
I just saw that there's `alpha.spacedock.info`. Nevermind lol.

**Comment by RedstoneWizard08** [comment]
Done in #466!

**Comment by HebaruSan** [comment]
Cool! 🎉 

> What I would like is to be able to filter on the browse API with more parameters like `game_id` and `game_version` to allow for easier use.

Did you decide `game_version` wasn't needed?

**Comment by RedstoneWizard08** [comment]
I should probably fix that lol

**Comment by V1TA5** [comment]
We should update the api doc to reflect the new abilities.

**Comment by RedstoneWizard08** [comment]
@HebaruSan I'm not going to add `game_version` since it's not available on the Mod's base class, and I don't want to slow down the query. I think it'll be okay though.

**Comment by V1TA5** [comment]
Game_version is a different db table from game id. Thats possibly why.

**Comment by RedstoneWizard08** [comment]
Yeah.

**Comment by V1TA5** [comment]
I dont know how large the impact is. ATM cpu load on the server isnt a big problem. 
Its your chance to tailor the API to your needs :)

**Comment by HebaruSan** [comment]
Checking the other table is possible:

https://github.com/KSP-SpaceDock/SpaceDock/blob/dbd67221961376193983028c8977c51b5296204d/KerbalStuff/search.py#L78-L79

**Comment by RedstoneWizard08** [comment]
alr im adding it

**Comment by RedstoneWizard08** [comment]
It's added!

**Comment by V1TA5** [comment]
Now everything has to go trough testing and we have to put it on production. 
Its up to @HebaruSan to tell me when that should be done.
