### ISSUE TITLE
Add additonal authors

### ISSUE THREAD

**Issue by zer0Kerbal** [KSP-SpaceDock/SpaceDock#468]
### Description (What went wrong?):
> per direct msg conversation on KSP forums

### Expected Behavior (What do you think should have happened instead?):

* [ ] to be added as author to https://spacedock.info/mod/618
* [ ] once added, listing should also show up on additional authors profile, currently it doesn't.

**Comment by V1TA5** [comment]
![image](https://user-images.githubusercontent.com/14166911/224469500-8fd59dfa-9394-4c8f-a27c-7b6c3032e974.png)

**Comment by V1TA5** [comment]
Users shouldn't be able to edit mods they are not author of.
