### ISSUE TITLE
advanced search

### ISSUE THREAD

**Issue by razerstrike** [KSP-SpaceDock/SpaceDock#473]
Description (What went wrong?):
advanced search wont turn off

Reproduction Steps (What did you do?):
look for the toggle button on the screen 

Expected Behavior (What do you think should have happened instead?):
turn it off

Environment (OS/Browser/Plugins/etc):
MacOS

Extra Information (Screenshots/Error Messages/Javascript Console Output):

showed terms

**Comment by HebaruSan** [comment]
![image](https://user-images.githubusercontent.com/1559108/223752501-f27fadff-ed77-4249-b73b-cdbf78e97dd1.png)

**Comment by HebaruSan** [comment]
@rayder27 this is the issue you were looking for.
