### ISSUE TITLE
Alter Mod overview page for games with no mods

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#484]
Hiding games with no mods will prevent them from getting some.
Solution:
Beautify the mod overview page. Instead of empty sections have a centered text with the rocket out of the box icon in SD clue that reads something along the lines of "This Game has no mods yet. Be the first to upload one!"

**Comment by HebaruSan** [comment]
> Hiding games with no mods will prevent them from getting some.

I'd just like to point out, yet again, that _showing_ Balsa (for _years_?) did not result in it getting even a single mod uploaded. Kitbash Model Club (FKA Balsa) simply doesn't have a modding community. There is no one to attract to the site.

<https://steamcommunity.com/app/977920/workshop/>
![image](https://user-images.githubusercontent.com/1559108/230652120-5b2b3a2c-21eb-41c3-9b58-42d1ffbdf6a0.png)
![image](https://user-images.githubusercontent.com/1559108/230652253-426a233a-4d54-4a3d-980c-0b7584185b29.png)

**Comment by V1TA5** [comment]
It might be a valid discussion if we want to offer support for balsa. Hiding any new game will defeat the purpose of adding it at all.
So either show it or remove/deactivate it.

**Comment by HebaruSan** [comment]
> Hiding any new game will defeat the purpose of adding it at all.

Not at all.

![image](https://user-images.githubusercontent.com/1559108/230685008-d081aa2e-fd42-4661-a534-c87fd3623da5.png)

**Comment by HebaruSan** [comment]
Fixed in #492
