### ISSUE TITLE
Thumbnail image artefacts

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#489]
Thumbnail images (in particular on the game overview page with its larger boxes) show quite a lot of artifacts.
We should up the jpg quality setting of the image lib that re-encodes all uploaded images.

**Comment by HebaruSan** [comment]
Looks like there's already a configuration setting for that, defaulting to 80:

https://github.com/KSP-SpaceDock/SpaceDock/blob/707f1afc04028a34989402f744e3f2e39bf739b5/KerbalStuff/thumbnail.py#L25-L29

Try adding this to `config.ini`:

```ini
thumbnail_quality = 95
```

(... or whatever value you feel appropriate)

**Comment by V1TA5** [comment]
oh yes youre right. i also think its not the quality if thats 80 already. i will up the resolution a bit. it will affect only new thumbnails?

**Comment by HebaruSan** [comment]
Yes, as far as I know there is no automatic regeneration when that setting is changed. But if you clear the `game.thumbnail` SQL column, I believe it would force it to regenerate.
