### ISSUE TITLE
New game: IXION

### ISSUE THREAD

**Issue by Olympia-H** [KSP-SpaceDock/SpaceDock#499]
Hi, is there a process for requesting games to be added to SpaceDock?

IXION is a recent space-themed game that I think would suit SpaceDock. It doesn't have an established modding community yet, so I'm currently working on a "BepInEx for IXION" pack that's setup to work with the game, similar to KSP2.

- <https://www.kasedogames.com/ixion>

Announcements for game versions:

- <https://store.steampowered.com/news/app/1113120>
- <https://store.steampowered.com/feeds/news/app/1113120>

**Comment by HebaruSan** [comment]
Hi @Olympia-H, see https://github.com/KSP-SpaceDock/SpaceDock/issues/433#issuecomment-968922066; @V1TA5 needs somebody to be SpaceDock's contact person for this game, so if you're willing to do that, it should be possible.

**Comment by Olympia-H** [comment]
Ok great thank you, yes I can do that

**Comment by Olympia-H** [comment]
For reference, the current game version is `1.0.4.7`
There haven't been any mods for the game yet, so I'm not sure whether you need to add previous versions
My bundle is ready for initial release, so there will be something to upload when you're ready

**Comment by Olympia-H** [comment]
For the versions? Ok, I doubt there will be many more updates, so I'm happy to submit them manually if it helps. They also might not be open to supporting modding

**Comment by HebaruSan** [comment]
I mentioned in Discord that an XSLT stylesheet that extracts the versions from Steam's RSS announcements feed for this game. It's very incomplete and not ready for production use, but I'm parking it here in case we decide to come back and flesh it out later.

```xslt
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom">

    <xsl:output method="text" />
    <xsl:strip-space elements="*" />

    <xsl:template match="channel">
        <xsl:apply-templates select="item" />
    </xsl:template>

    <xsl:template match="item">
        <xsl:variable name="version">
            <xsl:call-template name="get-version">
                <xsl:with-param name="string"
                                select="title" />
            </xsl:call-template>
        </xsl:variable>
        <xsl:if test="string-length($version) &gt; 0">
            <xsl:value-of select="$version" />
            <xsl:text>
</xsl:text>
        </xsl:if>
    </xsl:template>

    <xsl:template name="get-version">
        <xsl:param name="string" />
        <xsl:variable name="piece1">
            <xsl:choose>
                <xsl:when test="contains($string, ' ')">
                    <xsl:value-of select="substring-before($string, ' ')" />
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="$string" />
                </xsl:otherwise>
            </xsl:choose>
        </xsl:variable>
        <xsl:choose>
            <xsl:when test="contains($piece1, '.')">
                <xsl:value-of select="$piece1" />
            </xsl:when>
            <xsl:when test="contains($string, ' ')">
                <xsl:call-template name="get-version">
                    <xsl:with-param name="string"
                                    select="substring-after($string, ' ')" />
                </xsl:call-template>
            </xsl:when>
            <xsl:otherwise></xsl:otherwise>
        </xsl:choose>
    </xsl:template>

</xsl:stylesheet>
```

```
$ wget -q -O - https://store.steampowered.com/feeds/news/app/1113120 | xsltproc ixion-rss-versions.xslt -
1.0.4.7
1.0.3.6
1.0.2.2
```

**Comment by Olympia-H** [comment]
Well it's up to you, but that looks like more work than just adding it manually. I doubt there will be many more updates, probably just a few bugfixes.

**Comment by V1TA5** [comment]
ok, lets wait 1 week if the devs get back to me. If not ill give you an url where you can add new version numbers into a list.
As of now theres no rights management in spacedock. so either i would give you full admin or none. Thats a thing we have to work arround a bit.

**Comment by Olympia-H** [comment]
Well, the community manager reached out and seemed to want an update once we have everything setup and ready for users. They said they're unfamiliar with modding. I think it's a smaller indie studio, and I couldn't find any mods on their last game (Warhammer Mechanicus), so maybe it's something new for them.

**Comment by V1TA5** [comment]
Cool. if he wants to contact me directly he has my email. 
All i have to do is add the game to the db. I will do that today.
Can you list all version numbers up to now so i can add them?

**Comment by Olympia-H** [comment]
1.0.0.0
1.0.0.3
1.0.1.1
1.0.1.2
1.0.1.4
1.0.2.2
1.0.3.6
1.0.4.7 (current)

**Comment by Olympia-H** [comment]
Great, thanks for this! The initial uploads are done.

Also, just for reference, there's another game called Ixion (mostly lower case), but I've always seen this as IXION (all upper case) to distinguish them. Just wanted to point that out in case it's an issue

**Comment by V1TA5** [comment]
ok. 
It will be a Problem if we would add that game but i doubt it.

**Comment by HebaruSan** [comment]
Closing because this was added. 🎉

**Comment by V1TA5** [comment]
@Olympia-H SO you deleted all mods....

**Comment by V1TA5** [comment]
No feedback from @Olympia-H so ill deactivate the game again until someone wants to maintain it.
