### ISSUE TITLE
Add a suggest a feature button.

### ISSUE THREAD

**Issue by ThaZeus** [KSP-SpaceDock/SpaceDock#50]
I think it would be a good idea to put in a suggest a feature button to the very bottom of every page next to the API and source code.

**Comment by EIREXE** [comment]
Unecessary, that's what the issue tracker is for, if anything I would add a link to the issues page.

**Comment by ThomasKerman** [comment]
There's a link to this repo already, and therefore the issue tracker is linked too. Closing
