### ISSUE TITLE
Help with mathematical models

### ISSUE THREAD

**Issue by expolrer** [KSP-SpaceDock/SpaceDock#507]
Description (What went wrong?):
I want to use the mathematical model of Falcon 9 rocket to complete the project related to rocket recovery. Could you please give me some help, especially the rocket model source code in matlab or python? If not, please forgive my offense

Reproduction Steps (What did you do?):

Expected Behavior (What do you think should have happened instead?):

Environment (OS/Browser/Plugins/etc):

Extra Information (Screenshots/Error Messages/Javascript Console Output):

**Comment by HebaruSan** [comment]
Hi @expolrer, this repo is for the software behind a web site that hosts mods for a video game. Your query does not appear to relate to that; I would suggest starting with a search engine.
Closing as off-topic.
