### ISSUE TITLE
Unable to delete previous versions of uploaded mod

### ISSUE THREAD

**Issue by iLikeGothMommys** [KSP-SpaceDock/SpaceDock#509]
Description (What went wrong?):
When deleting previous version of my mod it takes me to a page that says "Clearly you've broken something. Maybe if you refresh no one will notice."

Reproduction Steps (What did you do?):
Go to "changelog" on mod page, press delete version & confirm

Expected Behavior (What do you think should have happened instead?):
I expect this to delete my previous version

Environment (OS/Browser/Plugins/etc):
Chrome, firefox, edge, supermium

Extra Information (Screenshots/Error Messages/Javascript Console Output):

**Comment by HebaruSan** [comment]
Thanks for the report. This was fixed in dbd0b5354326ddfe237bf5e1529eba201c595be9, awaiting merge to master/production when @V1TA5 has time.
