### ISSUE TITLE
Update and Improve Documentation

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#52]
Just to spin up a new instance of the website.

We will cover the infrastructure for SpaceDock separately.

**Comment by EIREXE** [comment]
I know most of the code, if anyone wants to ask anything I can help out.

**Comment by ILM126** [comment]
I do see the need for updating the Readme.md with the latest installation directions, seeing that I would like to try and set up SD for the first time soon.

@EIREXE Well, I am just curious to see how SD runs. Both in the frontend and backend. And from what I can tell on the front page, SD is a JavaScript/Python site. Still learning how to code here so I am unsure how I should tackle this site.
