### ISSUE TITLE
TAB to search.

### ISSUE THREAD

**Issue by connorprice** [KSP-SpaceDock/SpaceDock#59]
Currently using the TAB to search feature found in Google Chrome still directs you to the old KerbalStuff URL.

**Comment by phmayo** [comment]
Ah, that's the search engine autodiscovery, @Thomas

**Comment by TN-1** [comment]
You can fix this by going to chrome://settings/ , Clicking "Manage Search Engines" and by modifying the entry to say spacedock.info instead of kerbalstuff.com

**Comment by ThomasKerman** [comment]
Not a software bug, closing.
