### ISSUE TITLE
PR and Issue Templates?

### ISSUE THREAD

**Issue by FrikFry** [KSP-SpaceDock/SpaceDock#60]
https://github.com/blog/2111-issue-and-pull-request-templates

Might be useful to get a bit of a standardized format for bug reports. What do others think?

**Comment by TN-1** [comment]
I agree, Better to get all the info at the start instead of having to message back and forth forever

**Comment by ILM126** [comment]
Wow, I agree that this new feature would be very helpful.

**Comment by ThomasKerman** [comment]
Seconding this. :wink:

**Comment by TN-1** [comment]
For issues template, I think we should have some fields like:
Expected behavior
Actual behavior.
Steps to reproduce the problem
OS/Browser version, Relevant plugins, Etc

**Comment by EIREXE** [comment]
Screenshots and javascript console output would be useful too.

**Comment by FrikFry** [comment]
```
Description (What went wrong?):


Reproduction Steps (What did you do?):


Expected Behavior (What do you think should have happened instead?):


Environment (OS/Browser/Plugins/etc):


Extra Information (Screenshots/Error Messages/Javascript Console Output):


```

Thoughts?

**Comment by ThomasKerman** [comment]
:+1:

**Comment by TN-1** [comment]
Looks good

**Comment by TN-1** [comment]
Closed because it's been done
