### ISSUE TITLE
Detailed speed test for SpaceDock.info

### ISSUE THREAD

**Issue by Unknown601** [KSP-SpaceDock/SpaceDock#61]
seems to sit there for 50secs and do nothing then load

http://www.webpagetest.org/result/160218_1A_3S6/

**Comment by NecroBones** [comment]
I can't get any pages to load at the moment. And it was working great earlier after the speed tweaks.

**Comment by godarklight** [comment]
I believe this issue is now fixed - We've had a number of issues. The first being a hard drive failure, and the second being gunicorn choking on connections.

Feel free to reopen if needed.
