### ISSUE TITLE
Home Page Only Showing Featured Mods (Not also Newest Mods, Recently Updated Mods, and Popular Mods)

### ISSUE THREAD

**Issue by inigmatus** [KSP-SpaceDock/SpaceDock#63]
The page used to show 
Featured Mods, Newest Mods, Recently Updated Mods, and Popular Mods

in that order.

Now it only shows Featured Mods.

**Comment by inigmatus** [comment]
If you close a case, please comment on why it was closed or invalid.  Do we not want all four to populate?

**Comment by ThomasKerman** [comment]
This was done by SirCmpwn long time ago, and I like it that way. We can include a config option for that later, though. But for the moment, I will keep this closed

**Comment by inigmatus** [comment]
Works for me. Someone reported and darklight was in the dark concerning if it was intended or not.
