### ISSUE TITLE
Remove recipient list from "To" field in mod update emails

### ISSUE THREAD

**Issue by NecroBones** [KSP-SpaceDock/SpaceDock#68]
The recipients should be BCC (blind copied), rather than all listed in the "To" field for the mod update emails. Potential privacy issue.

**Comment by jwolff52** [comment]
So, pardon my lack of knowledge, but can BCC everyone on an email? That is, not have anyone in the To field?

**Comment by jkoritzinsky** [comment]
You would have the To field send back to the sender and BCC send to everyone on the list.

**Comment by NecroBones** [comment]
Yes, the "to" field is just informational, and can actually be omitted (though usually for cases like this it'll say "undisclosed recipients" or something similar). What matters is the "envelope" recipient list, which is handled as part of the SMTP protocol but not delivered to the end recipients in the message headers.

**Comment by jwolff52** [comment]
So how about using a [dictionary](https://docs.python.org/3/tutorial/datastructures.html)? with the recipient as  the Key and the  type (To, CC ,BCC, etc.) as the value? That way if (in the future) we need to use the  other fields the support is there? I do not know much about python andeven less about celery for that matter so please tell me if I am being insane :)

**Comment by NecroBones** [comment]
I'm pretty new to Python too (Perl guy here), but it makes me wonder what KerbalStuff did, since I don't think it had this problem.

**Comment by NecroBones** [comment]
I haven't tried pulling a branch to play with things yet, but so far to me it looks like a simple fix for now would be to simply comment out the line that reads "message['To'] = ";".join(group)" in "celery.py":

`for group in chunks(recipients, 100):
        #message['To'] = ";".join(group)
        print("Sending email from {} to {} recipients".format(sender, len(group)))
        smtp.sendmail(sender, group, message.as_string())`

Or change that line to something like:

`message['To'] = "undisclosed recipients;"`

It looks like the same function is called whether the email is an activation message for one person, or it's a mod-update announcement going to thousands.

**Comment by jwolff52** [comment]
I mean yeah, plus (from what I understand) the current email implementation is just glue so at this point would it be most beneficial to just put a different type of glue on and later when we come back and nail the whole thing down to give a proper fix then? Sticking with the metaphor of course.

**Comment by jwolff52** [comment]
I have implemented the dictionary (I think) but I am having issues getting my environment set up properly because it is on Ubuntu 12.04 :|

**Comment by NecroBones** [comment]
Obviously it would be more elegant to either pass a flag that tells it whether or not to suppress the "To" list, or pass the field-type with the list as you're suggesting. But just hiding it for now would close the privacy issue until we can clean it up. Band-aid fix. :)

I'm running CentOS over here. I'm hoping that's not too bad. ;)

**Comment by NecroBones** [comment]
I went back and looked at some of the old mod-update announcements from KerbalStuff, and it looks like it's always populated the "To" field, but individually, so I suspect it didn't used to use the chunking method that's in SpaceDock now. It's more efficient to chunk/group the outbound emails of course. An omitted or generic "To" field is fine from an SMTP perspective, but it's also possible that some recipient servers may score it slightly differently in terms of spam probability. Nevertheless, it's still preferable to exposing everyone's email addresses.

One alternative of course is just to undo the chunking/grouping and send to every recipient individually, then we wouldn't need to hide anything in the "To" field.

**Comment by NecroBones** [comment]
Created a PR with a bandaid fix to send to single recipients instead of chunking in 100s. If people don't like that solution, we can ditch it and do one of the other ideas.

**Comment by EIREXE** [comment]
@NecroBones sending emails one at a time will potentially break it, I already tried this before, and a big part of the messages simply don't go out.

Best solution IMO is to get BCC working.

**Comment by NecroBones** [comment]
OK cool.

**Comment by NecroBones** [comment]
OK, created a new PR that merely comments out the "To", effectively making it BCC. Not tested. Slightly higher chance of having messages treated as spam, but permits chunking the messages.

**Comment by NecroBones** [comment]
Actually I think it'll be cleaner to define it as "undisclosed-recipients:;" Going to close the PR and replace it with that. Sorry for the spam. New to this.
