### ISSUE TITLE
Suggestion:  Updated != New

### ISSUE THREAD

**Issue by KSPSnark** [KSP-SpaceDock/SpaceDock#73]
The front page has a "Newest Mods" and a "Recently Updated Mods" section.

A long-standing pet peeve of mine:  Currently (and on Kerbal Stuff, since forever), it treats a new mod as being "updated", which means any time someone posts a new mod, it appears twice on the page (at the top of both the "new" and "updated" lists).

Suggestion:  Alter the logic for "Recently Updated" so that it *only* shows mods that have more than one version.

Rationale:  There's not a lot of use in a mod showing up twice on the page.  It means that the existing mods who are actually *updated* don't get as much screen time because the new mods are elbowing them out.  Seems more helpful to treat "new" and "updated" as different things, since both sections are present.

Thoughts, anyone?

**Comment by godarklight** [comment]
Sounds perfectly reasonable to me ;)

**Comment by NecroBones** [comment]
Agreed.
