### ISSUE TITLE
[Feature] We Need a page for people who would like to donate that links to patreon

### ISSUE THREAD

**Issue by Unknown601** [KSP-SpaceDock/SpaceDock#77]
https://www.patreon.com/user?u=2903335&ty=p

**Comment by Unknown601** [comment]
<TMA-1701> I think maybe you should put these two links somewhere eye-grabbing on the site so that users may see it, just as Wikimedia projects do
<TMA-1701> I do not want another nice site to get offline

**Comment by Unknown601** [comment]
it should be on Spacedock.info

**Comment by Unknown601** [comment]
OK i added a page on the wiki so now people can find the like to donate :P

**Comment by Olympic1** [comment]
[From reddit](https://www.reddit.com/r/KerbalSpaceProgram/comments/46hc0y/spacedock_is_now_fully_live_with_ckan_integration/d05xf99):

**CaptRR**
> Any way we could get a donate button put on the site somewhere? At least we could help get you guys some pizza's :)

**Comment by ILM126** [comment]
Would this be at the top of the page, like a notification and can be closed or more like a permanent feature with the link in the footer?
Or maybe both would be nice...

**Comment by FrikFry** [comment]
I feel like a notification at the top of the page ala Wikipedia should be reserved for times when we aren't pulling in enough money to make ends meet. A more subdued permanent link in the footer seems more appropriate for everyday display.

**Comment by jwolff52** [comment]
Agreed I always felt like that was very..."needy" for lack of a better term.

**Comment by godarklight** [comment]
![http://i0.kym-cdn.com/photos/images/facebook/000/224/313/can-i-have-wiki-meme.jpg](Can we have like 20 bucks?)

**Comment by FrikFry** [comment]
I think a configuration option for 'header-donation-link' wold be nice.

I'll work on adding this...

**Comment by Olympic1** [comment]
Merged in dev
