### ISSUE TITLE
3rd Party Storage Backend

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#8]
As suggested by @pfj in KSP-SpaceDock/KerbalStuff-Reborn#2, the Internet Archive offers an S3-alike API for file storage: https://archive.org/help/abouts3.txt

The limitation is that only FLOSS and CC (or Public Domain) content can be hosted this way.

However, I think it is a good idea to integrate them, and base our mirrors / CDN off of this as the canonical storage.

**Comment by Ghostt1** [comment]
i thinks it is a good idea to mirror everything downloadable from SpaceDock. When a download request is coming - provide a local file, or a link to a mirror. So that regular users and CKAN could download files, but take care of the server traffic. Is it possible ?

**Comment by V1TA5** [comment]
we have enough resources for now (i only have to get them going). i want to deversify the nodes owners and locations at some point but only to be on the safe side if someone withdraws his support.
