### ISSUE TITLE
Github pages site for development news, etc?

### ISSUE THREAD

**Issue by TN-1** [KSP-SpaceDock/SpaceDock#88]

**Comment by jwolff52** [comment]
Something Blog style perhaps? Or did you have sonething else in mind?

**Comment by TN-1** [comment]
Precisely. Like a weekly/bi-weekly thing that has a brief overview of the
happenings, think squads development notes. I'd be happy to take charge of
it and put together the site and the posts if there are no objections.

**Comment by jwolff52** [comment]
Doesn't the site already have a blog? I thought I had seen someone mention it, but I cant find it...

**Comment by TN-1** [comment]
It doesn't have one as far as I can see.

**Comment by jwolff52** [comment]
Then what is #84 referencing?

**Comment by ThomasKerman** [comment]
It has a blog, here: https://spacedock.info/blog

I don't feel like we need another site for PR and so on, when we have the KSP forums, Reddit, the SpaceDock blog, and the commit history. :wink:

**Comment by TN-1** [comment]
I didnt know that existed hence the suggestion, nevermind :)
