### ISSUE TITLE
Title bar is too wide on mobile

### ISSUE THREAD

**Issue by jwolff52** [KSP-SpaceDock/SpaceDock#89]
Description (What went wrong?):

To see the title bar you have to either zoom out or scroll to the right on mobile, both instances leave a lot of white space on the right side of the screen (see the screenshot below)

Expected Behavior (What do you think should have happened instead?):

The title bar should scale with the rest of the site.

Environment (OS/Browser/Plugins/etc):

Samsung Galaxy S4, Lollipop, Chrome, with similar effects on Firefox

Extra Information (Screenshots/Error Messages/Javascript Console Output):

[Screenshot](http://imgur.com/XCFfLqs)

**Comment by jwolff52** [comment]
I'm dumb, title bar is to "wide" not "side"...

**Comment by jwolff52** [comment]
Ok so I scrolled down to see how the rest of the site looked and I believe the actual issue is [this blurb of text](http://imgur.com/hnUanJx), not the title bar.

**Comment by jwolff52** [comment]
So I think what we need is to add the class 

    col-md-3 

to line 137 of index.html in the templates folder. 

However I am at work (and on mobile) so I cant even begin to see if that would work.

**Comment by FrikFry** [comment]
I'll look at this.

**Comment by FrikFry** [comment]
The fix for this is on dev.
