### ISSUE TITLE
Multiple KSP Versions

### ISSUE THREAD

**Issue by Starstrider42** [KSP-SpaceDock/SpaceDock#93]
This is a repost of KerbalStuff/KerbalStuff#77.

Would it be possible to add a feature for SpaceDock letting modders declare that a mod is compatible with multiple versions of KSP? For example, a mod might be compatible with KSP 1.0.2 through 1.0.5.

Possible user interfaces (in no particular order):
* Curse-style checkboxes
* Multi-valued select
* Text box accepting ranges (suggested by @apemanzilla)
* Min/max versions, as used by CKAN and AVC (suggested by @pjf)

**Comment by FrikFry** [comment]
Given that we already have a whitelist of KSP versions, it seems like the best way to tackle this from a UI perspective would be to use either checkboxes or a multi-select dropdown.

**Comment by EIREXE** [comment]
Due to how KerbalStuff works this could get messy, what I would recommend is making mod files be stores in a new type of object called ModVersion, and then add relationships to GameVersions instead of strings like how it's done now.

**Comment by godarklight** [comment]
@EIREXE CKAN does not support that, it only supports "one version" or it uses a "min_version" and "max_version" string.

If we do end up supporting multiple versioning metadata specifically for ckan, let's do what they do to make things easy.

**Comment by Starstrider42** [comment]
> If we do end up supporting multiple versioning metadata specifically for ckan...

Actually, my original request was to support users who access the site normally. The current single-version system encourages reporting the *latest* KSP version that works, IIRC, so people who play older versions of KSP (typically those with lots of mods) need to go to a lot of trouble to know if a mod update will work with their install.

**Comment by dbent** [comment]
See my comment [here](https://github.com/KSP-CKAN/CKAN/issues/1173#issuecomment-115749193) for what I think a reasonable UI for this would be.
